README.md, awswrangler/__init__.py, awswrangler/__version__.py, awswrangler/athena.py, awswrangler/cloudwatchlogs.py, awswrangler/exceptions.py, awswrangler/pandas.py, awswrangler/session.py, building/Dockerfile, building/build-docs.sh, building/build-lambda-layer.sh, docs/source/api/awswrangler.cloudwatchlogs.rst, docs/source/api/awswrangler.rst, docs/source/examples.rst, docs/source/index.rst, requirements.txt, setup.py, testing/template.yaml, testing/test_awswrangler/test_athena.py, testing/test_awswrangler/test_cloudwatchlogs.py, testing/test_awswrangler/test_pandas.py, testing/test_awswrangler/test_s3.py
Issue #17 
Add cloudwatchlogs module and bumping version to 0.0.1! :rocket:
=> Add cloudwatchlogs module and bumping version to 0.0.1! :rocket:

awswrangler/cloudwatchlogs.py, awswrangler/glue.py, awswrangler/pandas.py, building/build-docs.sh, building/build-glue-egg.sh, building/build-image.sh, building/build-lambda-layer.sh, building/deploy-source.sh, building/publish.sh, testing/run-tests.sh, testing/test_awswrangler/test_athena.py, testing/test_awswrangler/test_cloudwatchlogs.py, testing/test_awswrangler/test_pandas.py
Issue #20 
Description of changes: Add **sep** argument for to_csv function and others small improvements.
=> Add *sep* argument for to_csv function

awswrangler/redshift.py, testing/test_awswrangler/test_redshift.py
Issue #22 
Description of changes: Add mechanism to make Redshift handle bad connections
=> Add mechanism to make Redshift handle bad connections

awswrangler/athena.py, awswrangler/glue.py, awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Issue #24  
Description of changes: Adding support for Date type for pandas integrations.
=> Adding support for Date type for pandas integrations

awswrangler/__version__.py, awswrangler/exceptions.py, awswrangler/glue.py
Previously all partition columns where of the string type. The same
logic for non partition columns is reused to find out the type of the
partition column.
=> Partition columns now have correct type

awswrangler/exceptions.py, awswrangler/glue.py, awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Issue #26 
Add compression for Pandas.to_parquet and prepare the structures to do the same with Pandas.to_csv.
But for now the second is blocked by a [Pandas limitation](https://github.com/pandas-dev/pandas/issues/22555).
=> Add compression for Pandas.to_parquet

README.md, awswrangler/athena.py, awswrangler/glue.py, awswrangler/pandas.py, awswrangler/spark.py, docs/source/contributing.rst, docs/source/examples.rst, docs/source/index.rst, testing/template.yaml, testing/test_awswrangler/test_spark.py
Issue #29 
```py3
dataframe.write \
.mode("overwrite") \
.format("parquet") \
.partitionBy(["year", "month"]) \
.save(compression="gzip", path="s3://...")
session = awswrangler.Session(spark_session=spark)
session.spark.create_glue_table(dataframe=dataframe,
file_format="parquet",
partition_by=["year", "month"],
path="s3://...",
compression="gzip",
database="my_database")
```
```py3
session = awswrangler.Session()
session.athena.repair_table(database="db_name", table="tbl_name")
```
=> Add Spark.create_glue_table() and Athena.repair_table()

awswrangler/athena.py, awswrangler/data_types.py, testing/test_awswrangler/test_pandas.py
Issue #34 
Add support for timestamp with time zone for read from Athena.
=> Add support for timestamp with time zone for read from Athena

awswrangler/athena.py, awswrangler/glue.py, awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Normalize Athena names (tables and columns)
=> Normalize Athena names (tables and columns)

awswrangler/athena.py, awswrangler/session.py, testing/test_awswrangler/test_athena.py
Issue #38 
Add Athena Workgroup
=> Add Athena Workgroup

awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Normalizing partitions and casting columns names.
=> Normalizing partitions and casting columns names

README.md, awswrangler/data_types.py, awswrangler/exceptions.py, awswrangler/glue.py, docs/source/divingdeep.rst, testing/test_awswrangler/test_pandas.py
Issue #44 
Documenting the null object columns issue.
=> documenting the null object columns issue

README.md, docs/source/installation.rst
Issue #46 
Make explicit that there is not support for Glue PySpark by now
=> Make explicit that there is not support for Glue PySpark by now

awswrangler/pandas.py, testing/test_awswrangler/test_redshift.py
Issue #48 
Fix pandas to redshift cast feature
=> Fix pandas to redshift cast feature

awswrangler/pandas.py
The logs for this are currently producing a boolean array, like:
```
W1024 16:20:42.335944 140524353476352 pandas.py:1003] Dropping repeated columns: [False False False False False False False False False False False False
False False False False False False False False False False False False
False False False False False False False False False False False False
False False False False False False False False False False False False
False False False False False False False False False False False False
False False False False False False False False False False False False
False]
```
This makes it so that it prints the names of the columns instead:
```
Dropping repeated columns: ['duplicated_col_name']
```
By submitting this pull request, I confirm that my …
=> Log the names of duplicated columns and not boolean array

README.md, building/build-docs.sh, building/build-glue-egg.sh, building/build-glue-wheel.sh, building/build-image.sh, building/build-lambda-layer.sh, building/deploy-source.sh, building/open-image.sh, building/publish.sh, docs/source/divingdeep.rst, setup-dev-env.sh, testing/build-image.sh, testing/open-image.sh, testing/run-tests.sh
Issue #52 
Description of changes: Documenting the usage of GeoPandas and non-picklable objects.
=> GeoPandas limitation explained in the docs 

awswrangler/athena.py, awswrangler/data_types.py, awswrangler/s3.py, testing/test_awswrangler/test_athena.py
=> Add Athena.query()

awswrangler/pandas.py, awswrangler/redshift.py, awswrangler/session.py, requirements.txt, testing/test_awswrangler/test_pandas.py, testing/test_awswrangler/test_redshift.py
Issue #37 
Add Pandas.read_sql_redshift()
=> Add Pandas.read_sql_redshift()

awswrangler/__init__.py, awswrangler/exceptions.py, awswrangler/sagemaker.py, awswrangler/session.py, testing/test_awswrangler/test_sagemaker.py
=> Sagemaker output from job name

awswrangler/aurora.py, awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Aurora MySQL Load check the number of files loaded after commit
=> Aurora MySQL Load check the number of files loaded after commit

README.md, awswrangler/exceptions.py, awswrangler/sagemaker.py, docs/source/examples.rst, docs/source/index.rst, testing/test_awswrangler/test_sagemaker.py
=> Improving Sagemaker module

awswrangler/sagemaker.py, testing/test_awswrangler/test_sagemaker.py
Fixing sagemaker get_model() for xgboost
=> Fixing sagemaker get_model() for xgboost

awswrangler/aurora.py, awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Issue #74 
1. Also accepts Glue connection name option instead of only PEP 249 connections
2. Rolling back in case of failure
3. Handling special characters (escaping) 
=> Aurora improvements

awswrangler/aurora.py, awswrangler/pandas.py, awswrangler/s3.py, testing/test_awswrangler/test_pandas.py
Issue #74 
* Handling null values for Pandas.to_aurora()
* Handling eventual consistency for Aurora postgres load
=> Handling null values for Pandas.to_aurora() and eventual consistency for postgres load

awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Issue #112 
Handling categorical partitions
=> Handling categorical partitions

awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Fixing bug to unload null values from Aurora
=> Fixing bug to unload null values from Aurora

awswrangler/pandas.py, awswrangler/redshift.py, testing/test_awswrangler/test_pandas.py, testing/test_awswrangler/test_redshift.py
Issue #114 
Handling empty results for Pandas.read_sql_redshift()
=> Handling empty results for Pandas.read_sql_redshift()

awswrangler/glue.py
Solves an issue with the serde not being defaulted: https://github.com/awslabs/aws-data-wrangler/issues/123
And solves this issue: https://github.com/awslabs/aws-data-wrangler/issues/122 by adding/cleaning a docstring.
Defaults to the serde `OpenCSVSerDe` in `glue.csv_table_definition`.
=> Defaults serde in glue.csv_table_definition

awswrangler/pandas.py
We are currently manipulating each pandas.read_csv parameter individually and setting default values in case they were missing. A safer approach would be to forward them and let pandas handle default values.
=> Forward all pandas kwargs

awswrangler/pandas.py, testing/test_awswrangler/test_pandas.py
Add filename and header arguments for Pandas.to_csv().
=> Add filename and header arguments for Pandas.to_csv().

awswrangler/pandas.py
*Issue #151*
In python 3.7 or above people get the error:
`AttributeError: module 'multiprocessing' has no attribute 'connection'`
To fix this, instead of using `mp.connection.Connection` to make the Type Hints now we import `Connection` from `multiprocessing.connection`:
```python3
from multiprocessing.connection import Connection
```
And to be more meaningful `Connection` was aliased as `MultiprocessingConnection`.
In some circumstances a get the same error using Python 3.6.9 on Manjaro, but using the same Python version on Ubuntu works and these changes fix for these cases as well.
Closes #151 
=> Fixes type hint non using direct import from 'multiprocessing'

awswrangler/athena.py
When we are trying to use pandas.to_redshift function, a columnName has double underscore, like `__dc_timelabel`
This internally call to_s3, which is trying to `normalize_columns_names_athena`. This ended up with columnName `dc_timelabel` in redshift and it's unexpected behavior.
The issue is athena actually support repeated underscores, we should not remove it.
disable the rule of remove repeated underscores in function `normalize_columns_names_athena` in athena.py
=> disable remove repeated underscores rule from _normalize_name as athena allows it

awswrangler/athena.py
Not able to create table with leading/trailing underscore in columnName, but this is allowed in athena
remove _normalize_name underscore strip
=> disable normalize name to remove underscore as underscore is allowed in athena columnName

awswrangler/catalog.py, awswrangler/s3.py, testing/test_awswrangler/test_data_lake.py
Issue #161
improving the column name sanitisation.
=> improving the column name sanitisation

awswrangler/athena.py, testing/test_awswrangler/test_data_lake.py
Issue #159 
Fixing athena queries for workgroups without encryption.
=> Fixing athena queries for workgroups without encryption

awswrangler/athena.py, testing/test_awswrangler/test_data_lake.py
Issue #160
Add categories arg to athena.read_sql_table
=> Add categories arg to athena.read_sql_table #160

awswrangler/s3.py, testing/test_awswrangler/test_data_lake.py
#167
Added validate_schema parameter to ParquetDataset arguments. 
=> added validate_schema parameter to read_parquet

awswrangler/s3.py
Issue #172
Fix missing boto3_session argument
=> Fix missing boto3_session argument #172

.pylintrc, awswrangler/_data_types.py, awswrangler/catalog.py, awswrangler/s3.py, docs/source/api.rst, testing/run-tests.sh, testing/test_awswrangler/_utils.py, testing/test_awswrangler/test_data_lake.py, testing/test_awswrangler/test_db.py
Issues #141 #170
Add Dataset feature to s3.to_csv.
=> Add Dataset feature to s3.to_csv #141 #170

awswrangler/s3.py, testing/test_awswrangler/test_data_lake.py
Issue #175
Add csv decompression for s3.read_csv
=> Add csv decompression for s3.read_csv #175

awswrangler/athena.py
Fixes two small bugs in `athena.read_sql_query`:
* Missing `/` in the path fstring between the s3 output and query id.
* Surfaces itself as a `WaiterError: Waiter ObjectExists failed: Max attempts exceeded` during runtime.
* Missing `boto3_session=session` in `s3.read_csv`.
* Surfaces itself as a `ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`
I noticed that my Athena queries were being run and stored as CSVs in S3 as expected but erroring before loading into a dataframe. After trying out these two fixes it's smooth sailing for me!
Really excited about this tool and keep up the great work!
=> fixing read_csv missing session token and broken s3 path

awswrangler/catalog.py
This is a modest change to the documentation. It adds a note to the the `sanitize_dataframe_columns_names`, explaining that it doesn't guard the user from collisions. 
Feel free to ignore if it's assumed that the user should know about this.
Example:
```python
import awswrangler as wr
d = {'Col1': [1, 2], 'col1': [3, 4]}
df = pd.DataFrame(data=d)
df_normalized = wr.catalog.sanitize_dataframe_columns_names(df)
In [13]: df_normalized
Out[13]:
col1  col1
0     1     3
1     2     4
In [16]: df_normalized["col1"]
Out[16]:
col1  col1
0     1     3
1     2     4
```
=> Adding a note about collisions for sanitize_dataframe_columns_names.

MANIFEST.in, awswrangler/py.typed, setup.py
While most of the module is annotated, the annotations are not registered and therefore can't be used outside of the module, when awswrangler is used as a library.
This PR adds a `py.typed` file to register these annotations. See PEP 561 for more details https://www.python.org/dev/peps/pep-0561/
=> Registering module's type annotations

README.md, awswrangler/__metadata__.py, testing/test_awswrangler/test_metadata.py
=> Bumping version to 1.0.4

awswrangler/catalog.py, awswrangler/s3.py
I think this behavior is closer to what boto3 api does, since it is not necessary to delete a table to create a new one. In my opinion, the "overwrite" mode should be specified explicitly rather than implicitly.
I find this situation quite problematic when I want to limit the permissions, for instance, to a lambda that will only create tables in glue catalog.
There are changes in two files:
- awswrangler/catalog.py: behavior when creating a non existing parquet table
- awswrangler/s3.py: adding optional mode parameter in store_parquet_metadata method
=> change _create_table (catalog.py) default behavior to do not remove table if exists

awswrangler/athena.py, awswrangler/db.py, awswrangler/s3.py, testing/test_awswrangler/test_data_lake.py
Issue #192
Add chunked=INTEGER option to ensure batch by number of rows reading Parquet files.
=> Add chunked=INTEGER option to ensure batch number of rows

awswrangler/_data_types.py, awswrangler/db.py, awswrangler/s3.py, testing/cloudformation.yaml, testing/test_awswrangler/test_db.py, tox.ini
Issue #197 
Add kms_key_id, max_file_size and region to Redshift Unload.
=> Add kms_key_id, max_file_size and region to Redshift Unload

.gitignore, awswrangler/_data_types.py, awswrangler/db.py, testing/test_awswrangler/test_data_lake.py
Issue #206
Add support to write nested types (array and struct).
=> Add support to write nested types (array and struct).

awswrangler/_utils.py
* Currently `awswrangler` ensures that at least some boto3 Session is
used when it calls AWS resources. However, since it creates a
`boto3.Session()` when non-null boto3 Session is passed as a
parameter, it completely sidesteps the ability of the user to set
parameters to the boto3 session that gets used by default (via the
`boto3.setup_default_session` function).
* This commit ensures that the `ensure_session` function uses boto3's
default session (reachable via `boto3._get_default_session()`) which
then also allows `awswrangler` users to set default parameters of the
boto3 Session it uses by default via `boto3.setup_default_session()`.
Signed-off-by: mr.Shu <mr@shu.io>
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> _utils: Make sure boto3's default session is used

awswrangler/_utils.py, testing/test_awswrangler/test_session.py, tutorials/02 - Sessions.ipynb
#245 
Hey @mrshu, I added some tests, updated the tutorial and I think that I found a more elegant way to use the boto3 default Session.
What do you think?
=> Add tests to the new default session.

testing/test_awswrangler/test_moto.py
#237 
Add test cases for `s3 delete objects` method
=> Add test raise s3 exception

testing/test_awswrangler/test_moto.py
add unit test for #271
Add a unit test for testing pandas argument and `encoding` and `newline` argument for the `fs.open` command(https://github.com/awslabs/aws-data-wrangler/blob/b57e2b7245e999191918022341943884e49b2e4e/awswrangler/s3.py#L1654) 
p.s. Because `pandas.read_csv` is in the `pandas.concat` section, a `TypeError` will raise when `concat` get a mock object returned from `pandas.read_csv`. So I used a try catch block to aviod the exception.     
=> add test for pandas argument and encoding

awswrangler/s3/_read.py, testing/test_awswrangler/test_moto.py
fix #290 
1. use `pandas_kwargs` to replace `pandas_args`
2. add a new unit test for confirming `pandas_kwargs` will be passed correctly when we call `read_csv` with chunksize.
=> Refactor naming of pandas kwargs

awswrangler/s3/_read.py, awswrangler/s3/_write.py
Expose `path_suffix` argument in `s3.store_parquet_metadata` function to allow filtering to specific file types under the root prefix.  This would support a use-case of ours in which we store a custom metadata file alongside folders containing Parquet files. Like:
```
root/
.custom_meta
partition=1/
foo.parquet
partition=2/
bar.parquet
```
Such a layout is already supported by PyArrow (ie, calling `pyarrow.parquet.ParquetDataset("s3://<bucket>/root/")` works fine), but since `awswrangler` tries to interpret every file/folder under `root/` as its own ParquetDataset, things break. In the above example, we would provide a `path_suffix=".parquet"`.
=> Allow providing suffix to s3.store_parquet_metadata

awswrangler/_data_types.py
astype("string") does not allow numeric characters so it seems to be a bug where we are casting a field that we want to be a decimal as a "string". We should use "str" instead.
=> setting dtype to decimal results in "StringArray requires a sequence of strings or pandas.NA" error

awswrangler/db.py
* Pass `s3_additional_kwargs` to `db.copy_files_to_redshift` and `db.write_redshift_copy_manifest` in order to support writing SSE/KMS encrypted manifests to S3
* In the same style as `db.copy_to_redshift`/`s3.to_parquet`
*Usage:*
Before:
```
awswrangler.db.copy_files_to_redshift(
...
)
```
```
ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```
After:
```
awswrangler.db.copy_files_to_redshift(
...
s3_additional_kwargs={
'ServerSideEncryption': 'aws:kms',
'SSEKMSKeyId': 'arn:aws:kms:...'
}
)
```
=> Support writing encrypted redshift copy manifest to S3

README.md
N/A
Add OKRA Technologies to "Who uses AWS Data Wrangler?"
=> Add OKRA to "Who uses"

awswrangler/catalog/_get.py
get_table_types example was failing with TypeError: got an unexpected keyword argument 'name' 
Updated get_table_types example to correct arg name "table"
=> Update get_table_types example

awswrangler/s3/_list.py
The S3 list_directories API examples has list_objects in code syntax instead of list_directories method
=> Fix typo in the list directories API documentation

awswrangler/athena/_read.py
There is a small typo in awswrangler/athena/_read.py.
Should read `practical` rather than `pratical`.
=> docs: Fix simple typo, pratical -> practical

docs/source/install.rst
New features supported with Glue version 2.0 includes automatic installation of packages using pip3.
Reference link: https://docs.aws.amazon.com/glue/latest/dg/reduced-start-times-spark-etl-jobs.html#reduced-start-times-new-features
=> Update installation doc for Glue PySpark Jobs

awswrangler/s3/_copy.py
- This PR is to add support for specifying extra s3 arguments to `copy_objects()`, the arguments get passed to the `ExtraArgs` in `boto3.resource('s3').meta.client.copy()` 
- Tested using `Mocked test environment` and the tests are passing
=> Add support for extra s3 args to copy_objects()

awswrangler/catalog/_get.py
Fix arg name from "name" to "table". 
Issue: 
Fix arg name from "name" to "table". In function table(), the args for table is "table" instead of "name". The example was leading to error: "TypeError: table() got an unexpected keyword argument 'name'"
=> Fix example args in def table()

awswrangler/db.py, awswrangler/s3/_copy.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py
Fix minor typo, change `KMY` to `KMS`
=> Fix typo KMY -> KMS

CONTRIBUTING.md, cloudformation/databases.yaml, cloudformation/delete-base.sh, cloudformation/delete-databases.sh, cloudformation/security-group-databases-add-local-ip.sh, cloudformation/security-group-databases-check.sh
New to the project and went through the steps to install the test environments. Thought some additional info/steps would help newcomers.
added:
- Optional step to set AWS_DEFAULT_REGION environment variable to control region test env uses.
- Scripts to delete Cloud Formation stacks once testing is complete.
- Script to take local IP and set at ingress for Database Security Group.
- Added note that Full Test environment contains RDS and Redshift which will incur cost.
=> Update contributing test setup

README.md
- datetime.now() requires importing datetime module
- Query had non-existing dimensions, removed them and replaced with the "my_dimension" so that it matches with dimension mentioned in wr.timestream.write()
=> FIX: Timestream sample in Readme

awswrangler/redshift.py
Issue 484
Description of changes:
Allow passing of raw aws s3 credentials for redshift copy/unload command
=> [feat] added raw s3 credential authentication for Redshift copy commands

awswrangler/athena/_read.py, tests/test_athena.py
*Issue #432:*
Add possibility to use `params` keyword for formatting the sql query which is ran against Athena. Only named parameters in the form `:name;` are accepted.
=> Add params to athena sql

setup.py
I forgot to add `awswrangler.dynamodb` to the `packages` list in `setup.py`. In order to prevent this from happening again use `find_packages()` instead of handling it manually.
=> Hotfix: Fix packages in setup

awswrangler/s3/_fs.py, awswrangler/s3/_write.py, awswrangler/s3/_write_text.py, requirements-dev.txt, tests/test_athena_csv.py, tests/test_s3_parquet.py, tests/test_s3_text.py, tests/test_s3_text_compressed.py, tutorials/004 - Parquet Datasets.ipynb, tutorials/011 - CSV Datasets.ipynb, tutorials/023 - Flexible Partitions Filter.ipynb
=> Add compression for to_csv() and to_json()

README.md
**Issue #, if available:**
None
**Description of changes:**
Fixes a hyperlink for "What is Amazon SageMaker Data Wrangler?"
=> Fix broken hyperlink in README

awswrangler/athena/_read.py, awswrangler/s3/_read_parquet.py
*Issue #521:*
Additional parameter `ignore_index` for function `s3.read_parquet()`. This parameter tells whether the index will be ignored/reset when combining multiple parquet files.
Additionally when running Athena queries, the index is always ignored as it does not contain additional information (only generated from the way that results are organized in the file the CTAS query creates)
PS: Minor fix in docstring of `s3.read_parquet_table()`.
=> Return DataFrame with unique index for Athena CTAS queries

.github/ISSUE_TEMPLATE/feature_request.md
When opening #536, I noticed the **feature** label wasn't applied automatically. Guessing it must match the exact name in the template.
=> Update feature issue template

awswrangler/_config.py, awswrangler/_utils.py, awswrangler/timestream.py, tests/test_config.py, tutorials/021 - Global Configurations.ipynb
*Issue #532:*
Adding the property `botocore_config` to `awsrangler.config` and using it for all `boto3` clients and resources if it is set.
However this change has some drawbacks:
1. Not all config properties are simple datatypes anymore and `botocore_config` cannot be set via environment variables.
2. The functionality is a little bit hidden, as it does not show up in the documentation itself but only in the configuration tutorial.
@igorborgest What do you think about this?
=> Add botocore Config to wr.config

CONTRIBUTING.md, CONTRIBUTING_COMMON_ERRORS.md
Adding a file for the common errors and the commands to fix the error.
I think if everyone help here we can create a database which will reduce the time to fix or create the environment
=> Adding files with the common errors and the fixes

awswrangler/redshift.py
Minor fix in docs for the wr.redshift.unload() method
```
wr.db.unload -> wr.redshift.unload
```
Mostly for my own future reference but thought I'd share it back =)
=> Minor Fix documentation for wr.redshift.unload

awswrangler/s3/_read_parquet.py
_read_parquet fails for a df which has a tz-aware column in the index. It drops tz information, because columns are moved (by _apply_index) to the index before tz information is applied to the remaining columns.
=> timezone should be applied before index is set

.bumpversion.cfg, CONTRIBUTING.md, requirements-dev.txt
*Issue #573:*
Adding `bump2version` for updating the version number in relevant files.
Usage: `bump2version major|minor|patch` and it will update the version number in all files given in `.bumpversion.cfg`, creates a commit with message `Bump version: {current_version} → {new_version}` and creates a tag with `{new_version}`.
A short How-To is also added to `CONTRIBUTING.md`.
=> Bump2version setup

awswrangler/cloudwatch.py, tests/test_redshift.py
- Datetime method needs to be UTC timezone aware, otherwise `datetime.datetime(year=1970, month=1, day=1)` will return a different timestamp value (potentially negative) depending on the user's timezone
- Set security token explicitly in Redshift test file
=> Making datetime timezone aware in CW module and adding security token in Redshift

requirements.txt
Bumping pg8000 version:
1.18 -> 1.19
=> Bumping pg8000 version to 1.19

.github/workflows/minimal-tests.yml, .github/workflows/static-checking.yml
Add minimal tests to the GitHub workflow.
=> Add minimal tests to the GitHub workflow.

awswrangler/mysql.py, awswrangler/postgresql.py, awswrangler/redshift.py, awswrangler/sqlserver.py, tests/test_mysql.py, tests/test_postgresql.py, tests/test_redshift.py, tests/test_sqlserver.py
*Issue #545:*
Add a flag for using the column names of the DataFrame in `to_sql` of `mysql`, `postgresql`, `sqlserver` and `redshift` for the creation of the `INSERT INTO` query. When the flag is set to `False` (the default), the behavior will stay the same, but when it is set to `True`, data will only be inserted into columns which exist in the DataFrame.
PS: @igorborgest Could you maybe run the new Redshift test as Redshift is unfortunately not available in AWS Educate.  `sqlserver`, `postgresql` and `mysql` are tested.
=> Add flag for using column names in to_sql

awswrangler/athena/_read.py, tests/conftest.py, tests/test_athena.py
#576
- Added optional `ctas_database_name` argument to store `ctas_temporary_table` in an alternative database (i.e. not the context database)
- This alternative database must exist and won't be created
- Added additional test in `test_athena_ctas`
=> Adding ctas_database_name argument

awswrangler/s3/_read_parquet.py, tests/test_s3_parquet.py
#580
Added a `map_types` boolean (set to True by default) to convert pyarrow DataTypes to pandas ExtensionDtypes. It is used to override the default pandas type for conversion of built-in pyarrow types or in absence of pandas_metadata in the Table schema.
=> Feature: Add flag to disable pyarrow DataTypes conversion

awswrangler/s3/_write.py, awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py, tests/test__routines.py, tests/test_athena_csv.py, tests/test_s3.py
#586
`path` argument is now optional. The code changes implementing this feature are based on the below logic tree:
```
if dataset is False:
if path is None:
raise Exception("you must pass `path`")
else:
no problem
else:
if database and table are None:
if path is None:
raise Exception("you must pass `path`")
else:
no problem
else:
if path is None:
if table exists:
path = catalog_path
else:
raise Exception("you must pass `path`")
else:
if table exists:
if path != catalog_path:
raise Exception("`path` must be equal to catalog path")
else:
no problem
```
Added and modified `s3` tests to evaluate impact
=> Major - Make path argument in wr.s3.to functions optional

awswrangler/_utils.py
Adding `user_agent_extra` argument to `botocore.config.Config` for reporting purposes
=> Minor - Adding userAgentExtra to botocore config

awswrangler/_config.py, awswrangler/_databases.py, awswrangler/mysql.py, awswrangler/postgresql.py, awswrangler/redshift.py, awswrangler/sqlserver.py, tests/test_config.py, tests/test_mysql.py, tests/test_postgresql.py, tests/test_redshift.py, tests/test_sqlserver.py
*Issue #599:*
Changing the generation of the `INSERT` sql query to include `chunksize` number of rows per query.
Additionally the RDS related tests now use a `pytest` fixture for the connections wherever possible, to ensure closing of the connection.
=> Insert multiple rows at once in to_sql

awswrangler/exceptions.py, awswrangler/s3/_merge_upsert_table.py, tests/test_s3_merge_upsert.py
#601
Instead of skipping the merge silently, the method raises an error when the quality check fails.
The schema from each dataframe is converted to Arrow schema and compared.
=> Raising exception when quality check fails

awswrangler/athena/_read.py, awswrangler/mysql.py, tests/test_mysql.py
https://github.com/awslabs/aws-data-wrangler/issues/608
Adding basic upsert capabilities to `mysql.to_sql()` function. 
`mode` supports 3 new values:
- `upsert_duplicate_key`: Performs an upsert using `ON DUPLICATE KEY` clause. Requires table schema to have defined keys, otherwise duplicate records will be inserted.
- `upsert_replace_into`: Performs upsert using `REPLACE INTO` clause. Less efficient and still requires the table schema to have keys or else duplicate records will be inserted 
- `upsert_distinct`: Inserts new records, including duplicates, then recreates the table and inserts `DISTINCT` records from old table. This is the least efficient approach, but handles scenarios where there are no keys on table.
By submitting this …
=> Mysql upsert

awswrangler/_data_types.py
#585
The `athena2pyarrow` method has recursive calls for `array`, `struct` and `map` types (i.e. it's calling itself for these types). We should therefore be passing the **original** dtype to each recursive call, not the **modified** [dtype](https://github.com/awslabs/aws-data-wrangler/blob/cf99eafb7b0f6a0a46a1c29357e1ed5d5a5a4680/awswrangler/_data_types.py#L256). Otherwise, the returned pyarrow type won't match the one in the table.
Example:
For a column `'onboardcountdetails': 'array<struct<CarRef:string,OnboardCount:int>>'` the current implementation of the `athena2pyarrow` would return a pyarrow type of `list<item: struct<carref: string, onboardcount: int32>>` (notice the lowercase `carref` and `onboardcount`) which causes a mismatch …
=> Fixing nested struct bug in athena2pyarrow method

awswrangler/s3/_write_dataset.py, awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py, tests/conftest.py, tests/test_s3_parquet.py, tests/test_s3_text.py
#617
In the `to_parquet` method, when `dataset=True`, created parquet file names are randomly generated based on a uuid hash. The aim of this PR is to prepend a prefix to these file names giving more control over the output parquet file names.
An optional `filename_prefix` argument, is added to the method, set to None by default. If supplied and dataset is True, a prefix is prepended to the output parquet file names.
Tested through `test_to_parquet_filename_prefix`.
=> Prepend prefix to to_parquet created files

awswrangler/s3/_read_parquet.py
*Issue #638*
Ensures that the path which is ultimately read when calling `read_parquet_table()` always ends with a "/" character.
This change avoids unwanted expansions when the `read_parquet()` function is called internally.
=> Ensure the table path read by 'read_parquet_table()' ends with "/".

awswrangler/s3/_read_parquet.py
*Issue #660:*
When available make use of the new `pyarrow` function `iter_batches`, but keep the old mechanism as a fallback for `pyarrow < 3.0.0`. 
I've opted for explicitly checking for the availability of `iter_batches` instead of a try except block, because of the `for` loop over the batches and to make sure that the two parsing mechanisms don't get mixed up in case of an unexpected exception.
=> Make use of pyarrow iter_batches

awswrangler/athena/_read.py, tests/test_athena.py, tests/test_athena_parquet.py
*Issue #659:*
When the result of a Athena CTAS query is empty, the column names and data types are retrieved from the create Glue table as a backup. 
However this is not possible for cached queries, as the Glue table does not exist anymore.
=> Add dtypes for empty ctas athena queries

awswrangler/catalog/_create.py, awswrangler/catalog/_definitions.py, awswrangler/s3/_write_text.py, tests/test_athena_csv.py
*Issue #672 :*
Adding `serde_library` and `serde_parameters` to `catalog.create_csv_table` for the possibility to use a different serialization library (OpenCSV) with the appropiate SerDe properties.
Default behavior wasn't changed.
Additional fix for `skip_header_line_count` to actually use the number given and not always 1.
=> Add serde parameters to csv table creation

awswrangler/catalog/_add.py, awswrangler/catalog/_definitions.py, awswrangler/s3/_write_text.py, tests/test_athena_csv.py, tests/test_catalog.py
#672
Added some enhancements to previous PR #673
- Leverage the `catalog_table_input` details when available to extract serde info from existing catalog tables
- Extend the logic to the `add_csv_partitions` method
=> Extending logic to add_csv_partitions and leveraging catalog_table_input

awswrangler/redshift.py, tests/test_redshift.py
*Issue #671:*
Add `overwrite_method = "drop" | "cascade" | "truncate" | "delete"` parameter to determine the way the table should be overwritten.
`drop` - plain `DROP ...` (`RESTRICT` by default) - drops the table, but will fail if there are any views that depend on it.
`cascade` - `DROP ... CASCADE` - drops the table, and all views that depend on it.
`truncate` - `TRUNCATE ...` - truncates the table, but [commits the current transaction](https://docs.aws.amazon.com/redshift/latest/dg/r_TRUNCATE.html), hence the overwrite is **not atomic**.
`delete` - `DELETE FROM ...` - deletes all rows from the table within the current transaction. Slow relative to the other methods.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Add Redshift overwrite methods

awswrangler/_databases.py, awswrangler/mysql.py, cloudformation/databases.yaml, tests/test_mysql.py
*Issue [#554](https://github.com/awslabs/aws-data-wrangler/issues/554):*
Pass SSL properties from Glue Connection to PyMySQL. ~~Depends on [this PyMySQL PR](https://github.com/PyMySQL/PyMySQL/pull/980) merged & released first. ~~
UPD: In conversation with PyMySQL contributors it seems it's possible to pass `SSLContext` to PyMySQL so extra argument is not required anymore.
=> Pass SSL properties from Glue Connection to MySQL

awswrangler/s3/_write_dataset.py
During testing some bucketing I've noticed a problem when there are combined datatypes in some rows which cause dtype casting during `df.apply`. As during `df.apply` each row is handled as a separate Series and for example there is a `float` and a `int` column, the `dtype` of the row series is `float` and the [Exception](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/s3/_write_dataset.py#L124) is raised.
To prevent this issue the fix according to https://stackoverflow.com/a/47145613/10608063 was added which changes the `dtype` to `object` before `apply`.
=> Fix bucketing types

awswrangler/s3/_write_text.py
*Issue #724*
Fix the docs regarding `dataset` parameter of `wr.s3.to_csv`
=> Minor - clarify wr.s3.to_csv docs

test_infra/requirements.txt, test_infra/stacks/base_stack.py, test_infra/stacks/databases_stack.py, tests/test_moto.py
*Issue: N/A*
CB infra has a dependency on specific VPC tag & one of the SSM parameters that weren't directly used by any tests & was omitted during prev. PR. This PR:
- Adds tags to VPC
- Adds security group id SSM parameter
- Set test S3 region to us-east-1 to avoid having to specify location constraint
=> CDK test infra - Minor - Add missing SSM parameter

awswrangler/s3/_read_excel.py, awswrangler/s3/_write_excel.py, tests/test_s3_excel.py
#739 
Removing explicit Excel engine configuration from s3 read and write excel methods. Instead, Wrangler delegates engine choice to Pandas.
=> Removing explicit Excel engine configuration

awswrangler/s3/_describe.py, awswrangler/s3/_download.py, awswrangler/s3/_fs.py, awswrangler/s3/_list.py, awswrangler/s3/_read.py, awswrangler/s3/_read_excel.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_read_text.py, test_infra/stacks/base_stack.py, tests/test_s3_excel.py, tests/test_s3_parquet.py, tests/test_s3_text.py
*Issue #721 *
Add `version_id: Optional[Union[str, Dict[str, str]]]` parameter to S3 read operations to be able to query specific versions of an object or mulptiple objects. The parameter, depending on the context of the operation, may be either a single version id string or a dictionary `object key -> version id`.
Tests coming up.
=> Add VersionId parameter for S3 reads

.bumpversion.cfg, CONTRIBUTING_COMMON_ERRORS.md, README.md, awswrangler/__metadata__.py, awswrangler/athena/_read.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_read_text.py, awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py, building/lambda/Dockerfile, docs/source/install.rst, docs/source/what.rst, requirements-dev.txt, setup.py, tests/test_metadata.py, tests/test_s3_excel.py, tests/test_s3_select.py, tox.ini, tutorials/001 - Introduction.ipynb, tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server.ipynb, tutorials/014 - Schema Evolution.ipynb, tutorials/021 - Global Configurations.ipynb, tutorials/022 - Writing Partitions Concurrently.ipynb, tutorials/023 - Flexible Partitions Filter.ipynb
*Issue #, if available:* N/A
- Bumping version
- Python 3.6 compatibility fixes
=> Preparing release 2.9.0

awswrangler/redshift.py, tests/test_redshift.py
#760 
Adding an `unload_format` parameter to the `wr.redshift.unload_files` method, enabling unloading files as a CSV instead of just parquet. Parameter defaults to PARQUET if None is supplied, meaning the change is backward compatible.
=> Minor - Adding unload format to unload_files

awswrangler/s3/_write_text.py, docs/source/api.rst, tests/test_s3_text.py
*Issue #765*
Add header support for CSV datasets.
=> Add header support for CSV datasets

awswrangler/athena/_read.py, tests/test_athena.py
*Issue #785*
`wr.athena.read_sql_query` has CTAS as an option, but it does not support bucketing. Bucketing may be used, among other things, to make athena produce exactly one output file that can be read without result ordering concerns.
=> Add CTAS bucketing to wr.athena.read_sql_query

awswrangler/_databases.py, awswrangler/_utils.py, awswrangler/mysql.py, awswrangler/postgresql.py, tests/test_postgresql.py
*Issue #807:*
Adding `upsert` support for postgres. However, in contrast to `mysql` only a single `upsert` mode exists, as in my eyes it is the only one which makes sense in a generic way for postgres (still I'm open to extending the modes).
=> Add postgres upsert

README.md
Add Getting Help section to README
=> Add Getting Help section to README

awswrangler/athena/_read.py
Athena read_sql_query was raising errors locally when using given boto3_session, because the catalog.get_table_types call didn't get the boto3_session from caller.
=> Add boto3_session parameter to catalog.get_table_types

awswrangler/athena/_read.py, awswrangler/athena/_utils.py, awswrangler/mysql.py, awswrangler/redshift.py, awswrangler/s3/_copy.py, awswrangler/s3/_delete.py, awswrangler/s3/_describe.py, awswrangler/s3/_fs.py, awswrangler/s3/_list.py, awswrangler/s3/_write_excel.py, awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py
*Issue #827:*
Use `botocores`'s `Loader` and `ServiceModel` for extracting the accpeted kwargs out of the json service definitions of `botocore` instead of having a manually maintained dict.
=> Use botocore for s3 kwargs

awswrangler/timestream.py, tests/test_timestream.py
*Issue #842 *
Add version param for wr.timestream.write
=> Add version param for wr.timestream.write

awswrangler/timestream.py, tests/test_timestream.py
Issue #838 
Support iterating over timestream query result pages
=> Add chunked mode to timestream.query

awswrangler/_config.py, awswrangler/_utils.py, awswrangler/dynamodb/_delete.py, awswrangler/dynamodb/_utils.py, awswrangler/dynamodb/_write.py
#881 
Add DynamoDB endpoint URL and apply configuration to all public methods in DynamoDB module
=> Enabling DynamoDB endpoint URL

awswrangler/_databases.py, tests/test_redshift.py
#874 
Handle the edge case where the Redshift table is empty. Currently an empty dataframe with no columns is returned. Fix returns an empty dataframe but with columns
=> Handle empty table corner case

awswrangler/redshift.py
I believe there is a tiny mistake in the example for Redshift.
Use `wr.redshift` instead of `wr.db` in Redshift code example.
=> Use redshift submodule in example

awswrangler/mysql.py
#918 
Adding backtick to column names in wr.mysql.to_sql to allow columns with names the same as reserved words to be used when using use_column_names=True
=> Adding backticks to insertion columns names

awswrangler/redshift.py
Issue #914
Remove extra cleanup on `unload_to_files`
=> Redshift - remove extra cleanup on unload_to_files

awswrangler/mysql.py, awswrangler/postgresql.py, awswrangler/redshift.py, awswrangler/s3/_write.py, awswrangler/s3/_write_text.py, awswrangler/sqlserver.py
#989
- Added error message to `EmptyDataframe` exception
=> Minor - Adding error message to EmptyDataframe exception

awswrangler/catalog/_create.py, awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py, tests/test_athena_projection.py, tests/test_config.py
Adding the possibility to add a custom storage location template for projection if it doesn't match the default name scheme.
=> Add storage location template for glue

awswrangler/s3/__init__.py, awswrangler/s3/_list.py, docs/source/api.rst, tests/test_s3.py
#997
Adding S3 list buckets public method
=> Adding S3 list buckets

awswrangler/s3/_write_parquet.py
#1045
Enable user to pass pyarrow write table `flavor` argument via `pyarrow_additional_kwargs`
=> Enable user to specify pyarrow flavor

pyproject.toml
If you try to install aws-data-wrangler with the current Python version `3.10.1` it says
it's not compatible and you only get offered a really old version 0.3.2.
This change makes it compatible with all Python 3.10 versions.
=> Allow all Python 3.10 versions

awswrangler/s3/_write_parquet.py, tox.ini
*Issue #1058 *
Fix tutorial link
=> Minor - Fix tutorial link

awswrangler/_utils.py, awswrangler/mysql.py, poetry.lock, pyproject.toml
=> Upgrading dependencies

docs/source/install.rst
The way how the AWS Data Wrangler Layer can used within CDK and SAR is
improved.
I opened this PR as a draft to allow discussions on how the description is enough or should be even extended, e.g. to more CDK languages or for using SAM templates as well. 
Resolves: #1097
=> docs(install): Improved CDK usage guidance

awswrangler/catalog/__init__.py, awswrangler/catalog/_utils.py, tests/test_athena.py
FIxes #1119 (hopefully)
I added: 
* One function `rename_duplicate_columns` which recursively appends `_n` to duplicated column names. 
* Added a flag to `sanitize_dataframe_columns_names` which can be `['warn', 'drop', 'rename']` will either leave the DF along, delete all but the first duplicated columns, or append a number to the duplicated column.
* Added some tests in `athena_test.py` to test this functionality. I'm not exactly sure this is the right place but other column sanitizers were there. 
* Exported `rename_duplicate_columns`
* Imported warnings.
I'm not sure if I followed how you handle warnings as I saw different syntax in other parts but it should be easy to modify if I was wrong. 
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Append incremental n to duplicate cols recursively

building/build-lambda-layers.sh, building/lambda/Dockerfile, building/lambda/build-docker-images.sh, building/lambda/build-lambda-layer.sh
Subject: Use Amazon Lambda base images to build aws-data-wrangler
- Feature
- lambci/lambda while useful is a bit behind on python versions/architectures support (3.9, 3.10, arm64)
- and now Amazon provide base images that can be used for lambda, and are likely good for our use case too
- this PR is not adding 3.9/3.10/arm64 support, this would be covered in a different PR.
- #1129
- By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> Use Amazon Lambda base images to build aws-data-wrangler

awswrangler/redshift.py, test_infra/poetry.lock, tests/test_redshift.py
Subject: Adding manifest parameter to 'copy_from_files 'method
- Feature
- New parameter for `redshift.copy_from_files(...)` : `manifest`
- New method `redshift._get_paths_from_manifest(...)`: Returns list of S3 paths declared in manifest file.
- [#1142 ](https://github.com/awslabs/aws-data-wrangler/issues/1142)
- By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
- Unit test written for method using new parameter.
```
> pytest tests/test_redshift.py::test_copy_from_files_manifest
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.7.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 …
```
=> Adding manifest parameter to 'redshift.copy_from_files' method

awswrangler/athena/__init__.py, awswrangler/athena/_read.py, awswrangler/athena/_utils.py, docs/source/api.rst, tutorials/006 - Amazon Athena.ipynb
- Feature
User can obtain the query string with:
```
sql = wr.athena.get_named_query_statement(named_query_id="id")
df = wr.athena.read_sql(sql=sql, database=default)
```
- #1177
=> Add Athena get_named_query_statement method

awswrangler/data_api/connector.py, tests/test_data_api.py
- Bugfix
- Columns with empty values are labeled with `isNull=True` in the [column metadata ](https://github.com/awslabs/aws-data-wrangler/blob/1f42b05e79f634346f4bd48d29be063ad66cc781/awswrangler/data_api/connector.py#L45)response of the Data Api. As result, the column type is erroneously assigned to Boolean instead of None.
- #1158
=> Fix isNull in data api connector

.github/workflows/git-hygiene.yml
Subject: Adding workflow for Git Hygiene
- New workflow for managing stale issues and pull requests
- Stale issues (issue with no activity in **60** days) will be scheduled for closure and closed after **7** number of days
- Stale pull requests (PR with no activity in **60** number of days) will be scheduled for closure and closed after **7** number of days
- Ancient issues of older than **730** days will be closed if they do not meet threshold: **5** of upvotes or recent activity.
- Runs periodically every **8** hours.
- Set in `dry-run` mode for now. We can test after merge and change this after validation.
- [Full list of configurable settings](https://github.com/aws-actions/stale-issue-cleanup/blob/main/action.yml#L6)
By submitting this pull request, I confirm that my contribution is …
=> Adding workflow for Git Hygiene

awswrangler/_data_types.py
Subject: Add map type support to redshift copy operation 
- Bugfix
- [ISSUE-1185](https://github.com/awslabs/aws-data-wrangler/issues/1185)
=> Add map type support to redshift copy operation

building/build-lambda-layers.sh, building/lambda/build-docker-images.sh
- Feature
- now that we have a base image with a version available for Python 3.9 we can create an awswrangler layer for it
- https://github.com/awslabs/aws-data-wrangler/pull/1162
- By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> Add Python 3.9 support to the build process

building/lambda/build-lambda-layer.sh
- Bugfix
- quick PR to use the latest release from Apache Arrow 6.0.x branch
- Release notes: https://arrow.apache.org/release/6.0.1.html
=> bump arrow from 6.0.0 to 6.0.1

awswrangler/_utils.py
-  S3 Proxy support with Data Wrangler
- Exposing `verify` argument for boto3 low-level service clients.
- [boto3.client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client)
- [boto3.resource](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client)
- #1128 
=> S3 Proxy support with Data Wrangler

building/build-lambda-layers.sh, building/lambda/build-docker-images.sh
- Feature
- Lambda's Python3.6 and Python3.7 runtimes are not supported on arm64. Avoid trying to build them when running the build project for Arm64.
=> arm64 support: do not build lambda layers for python3.6/3.7 when arch is arm64

awswrangler/athena/__init__.py, awswrangler/athena/_cache.py, awswrangler/athena/_read.py, awswrangler/athena/_utils.py, docs/source/api.rst, tests/_utils.py, tests/test_athena.py
- Feature
- Add `create_ctas_table` method to Athena module
- Refactor `read_sql_query` to use new method
- #1165
=> Add create_ctas_table to Athena module

awswrangler/athena/_read.py, awswrangler/athena/_utils.py, docs/source/api.rst, tests/_utils.py, tests/test_athena.py
- Enhancement
- Add `wait` parameter to Athena `create_ctas_table` method
- #1165
=> Add wait to create_ctas method

awswrangler/redshift.py, tests/test_redshift.py
- Support additional sql params in Redshift COPY operation
- Adding argument `sql_copy_extra_params` to `awswrangler.redshift.copy_from_files()` to support additional [SQL Params](https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-load.html#copy-statupdate)
- PyTest to evaluate the above.
- #1180 
=> Support additional sql params in Redshift COPY operation

awswrangler/athena/_read.py
- Bugfix
- Refactoring
- Unlike CTAS, user supplied S3 path should take precedence over Workgroup enforced S3 Output Location for UNLOAD method
- Refactor `_resolve_query_without_cache` as a result
- #1200
=> (fix): Give precedence to user path for Athena UNLOAD S3 Output Location

awswrangler/neptune/neptune.py, tests/test_neptune.py
Fixed ISSUE-1232 where writing property graph dataframes where columns contained NaN caused Gremlin query errors.  Added appropriate checks to ignore these.
- Bugfix
https://github.com/awslabs/aws-data-wrangler/issues/1232
=> Fixed ISSUE-1232 where writing property graph dataframes

test_infra/cdk.json, test_infra/stacks/databases_stack.py
- Feature
- Bugfix
- add test infrastructure for oracle database
- limit password to 30 characters as 32 characters (default from aws_secretsmanager) is too big for Oracle RDS
- update aurora postgresql from 11.6 to 11.13 as the former is no longer available
- #629
- #1259
=> add test infrastructure for oracle database

awswrangler/s3/_select.py
- Refactoring
At present, S3 select module relies on `pd.concat` to generate the Pandas dataframe. On second thought, concat is highly inefficient operation. It's both [slow and memory intensive](https://stackoverflow.com/questions/36489576/why-does-concatenation-of-dataframes-get-exponentially-slower). Creating a dataframe from a list could be more efficient here. Another advantage is that parallelizing operations on a list (e.g. using Ray) is simpler than on dataframes
=> (enhancement): Revisiting S3 Select performance

awswrangler/redshift.py, tests/test_redshift.py
This will prefer data from the file / tmp table when the precombine keys are equal.
Also fix up some inconsistencies in the docs.
- Feature
- Add precombine key to upsert method
- https://github.com/awslabs/aws-data-wrangler/issues/1292
=> Feature: Add precombine key to upsert method for Redshift

awswrangler/redshift.py
- Bugfix
- precombine_key kwarg not available on `redshift.copy()` function
- https://github.com/awslabs/aws-data-wrangler/issues/1292
=> pass precombine to redshift.copy()

awswrangler/redshift.py
- Feature
- Pass DataFrame column names to the _upsert function:
`insert_sql = f"INSERT INTO {schema}.{table}({column_names_str}) SELECT {column_names_str} FROM {temp_table}"`
instead of 
`insert_sql = f"INSERT INTO {schema}.{table} SELECT * FROM {temp_table}"`
- [Ticket](https://github.com/awslabs/aws-data-wrangler/issues/1314)
=> Use DataFrame column names in INSERT statement for UPSERT operation

awswrangler/_data_types.py
- Bugfix
- Modify athena2quicksight datatypes to allow startswith for varchar
- #1331
=> Modify athena2quicksight datatypes to allow startswith for varchar

test_infra/stacks/opensearch_stack.py
- changing our OpenSearch test instances from t3.small to t3.medium
=> [skip ci] move opensearch test infra from t3.small to t3.medium

awswrangler/_data_types.py
=> Fix extension dtype index handling

awswrangler/redshift.py
- Bugfix
-  Unable to use "upsert" mode when using the `wr.redshift.to_sql` method if the schema name contains a hyphen
- [Bug: Unable to use a schema with a "-"](https://github.com/awslabs/aws-data-wrangler/issues/1352)
=> Fix issue with redshift.to_sql() method when mode set to "upsert" and schema contains a hyphen

awswrangler/dynamodb/_read.py, awswrangler/dynamodb/_utils.py
=> (refactor): Refactor DynamoDB read_partiql method

awswrangler/__init__.py, awswrangler/_threading.py, awswrangler/_utils.py, awswrangler/distributed/__init__.py, awswrangler/distributed/_distributed.py, awswrangler/distributed/_pool.py, awswrangler/distributed/_utils.py, awswrangler/lakeformation/_read.py, awswrangler/s3/_select.py
- Refactoring
- Feature
- add ray pool & thread pool executor wrapper
- add single-path distributed s3 select impl
- refactor distributed lakeformation impl
=> Refactor threading/ray; add single-path distributed s3 select impl

awswrangler/redshift.py, tests/test_redshift.py
- Enhancement
- Enable passing kwargs to redshift_connector.connect
- #1463
=> (enhancement): Enable passing kwargs to redshift_connector.connect

load_tests/test_s3_select.py
- Adds dedicated directory for load tests for distributed wrangler methods
=> Adding subdir for Distributed Wrangler Load Tests

awswrangler/_config.py, awswrangler/_utils.py, tests/test_config.py
=> add timestream endpoint config prop

.github/workflows/bandit.yml, .github/workflows/cfn-nag.yml, .github/workflows/minimal-tests.yml, .github/workflows/snyk.yml, .github/workflows/static-checking.yml, .github/workflows/unlabel-assigned-issue.yml
- Security best practice
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows.
GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue. Merging this PR will also help improve the Scorecard score for this project.  
Signed-off-by: Varun Sharma <varunsh@stepsecurity.io>
`GITHUB_TOKEN` has `write` permissions …
=> ci: add GitHub token permissions for workflows

awswrangler/athena/__init__.py, awswrangler/athena/_read.py, tests/test_athena.py
- Feature
- Add `get_query_results` function to the Athena module. This function returns the results of an Athena's QueryExecutionId as a Pandas DataFrame. It also works with UNLOAD and CTAS queries
=> Add get_query_results to the Athena module

CONTRIBUTING.md, CONTRIBUTING_COMMON_ERRORS.md
1. An entry was added to [CONTRIBUTING_COMMON_ERRORS](https://github.com/awslabs/aws-data-wrangler/blob/main/CONTRIBUTING_COMMON_ERRORS.md) page which specifies that the IAM role used by CloudFormation needs to be added as a Lake Formation admin.
1. Fix instructions for how to run a unit test for the databases. This guide was previously referencing a non-existent test file.
https://github.com/awslabs/aws-data-wrangler/issues/1497
=> Updating CONTRIBUTING.md and CONTRIBUTING_COMMON_ERRORS.md

awswrangler/_arrow.py, awswrangler/_utils.py, awswrangler/athena/_read.py, awswrangler/distributed/_utils.py, awswrangler/distributed/datasources/__init__.py, awswrangler/distributed/datasources/parquet_datasource.py, awswrangler/lakeformation/_read.py, awswrangler/redshift.py, awswrangler/s3/_read.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_select.py, load_tests/test_s3.py, tests/test_athena.py, tests/test_athena_parquet.py, tests/test_redshift.py, tests/test_s3_parquet.py, tests/test_s3_select.py
- Feature
- Refactoring
1. Refactor `wr.s3.read_parquet` and other methods in `_read_parquet` S3 module to reduce technical debt:
- Leverage thread pool executor when possible
- Simplify chunk generation logic
- Reduce number of conditionals by generalising edge cases
- Improve documentation
2. Distribute both `read_file_metadata` and `read_parquet` calls
- `read_file_metadata` is distributed as a `@ray_remote` method via the executor
- `read_parquet` is distributed using a [custom datasource](https://docs.ray.io/en/latest/data/package-ref.html#custom-datasource-api) and the [`read_datasource`](https://docs.ray.io/en/latest/_modules/ray/data/read_api.html#read_datasource) Ray public API
- Standard tests are passing with minimal changes to the tests
- Two tests are added to the `load_test` …
=> (feat): Refactor to distribute s3.read_parquet

awswrangler/athena/_cache.py
- Bugfix
When preparing queries for comparisons, brackets are just stripped from the query string which in some cases leads to deeming queries unequal even if they are the same.
One example would be a query like:
```sql
SELECT *
FROM my_tbl
ORDER BY (col_1, col_2);
```
If i run this query twice against Athena it will think these are two different queries as it will just remove the `)` in the end.
To prevent cases like this, my proposal would be to just check for columns which encapsulate the complete query. I know that also this is not perfect, but at least is a little bit better that it is right now. However, this is debatable and I'm open for a discussion :slightly_smiling_face: 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Check for pair of brackets in query preparation for Athena cache

awswrangler/athena/_read.py, tests/unit/test_athena.py
- Bugfix
The current parameter replacement might replace parameter names that are merely prefixes of another parameter name. For example, for a query like
```sql
SELECT *
FROM table
WHERE col = :col AND col = :col2
```
replacing `col` with `"Name"` would result in the following query:
```sql
SELECT *
FROM table
WHERE col = 'Name' AND col = 'Name'2
```
With the change I've implemented, the parameter substitution is making use of the Regex negative look ahead operator, which ensures that we are only replacing full tokens. Therefore, `col2` will not be picked up by a replacement of `col`.
I also added the unit test `test_read_sql_query_parameter_formatting_respects_prefixes`, which will ensure this issue is caught by testing in the future. …
=> Fix query parameter replacement replacing partial parameter names

awswrangler/s3/_merge_upsert_table.py, tests/test_s3_merge_upsert.py
- Feature
The `s3.merge_upsert_table` function currently does not work when the destination Glue table is empty. If the Glue table is already created, we should be able to simply insert the data.
Closing #1562 
=> feature: Add support for upserting to an empty Glue table

awswrangler/s3/_merge_upsert_table.py
- Refactoring
- In the previous commit, the schema was unnecessarily fetched as a DataFrame only to be converted back to a dict. It turns out `wr.catalog` has a function to get the table types as a dict automatically.
=> refactor: Simplify code for merge_upsert_table

awswrangler/s3/_write_text.py, tests/test_s3_text_compressed.py
- Bugfix
- In `s3.to_json`, compression parameter is passed twice to the `_to_dataset` function (explicitely and via pandas_kwargs). Popping the value from the dictionary fixes the issue.
- #1582
=> (fix): to_json compression param is passed twice when dataset=True

tests/test_quicksight.py
- XFail For QuickSight Test failing with intermittent issue.
- Intermittent fail:
```
botocore.errorfactory.ConflictException: An error occurred (ConflictException) when calling the DeleteDataSource operation: Updating resource arn:aws:quicksight:us-east-1:658066294590:datasource/test would cause an internal conflict. Please try again later.
```
=> XFail for QuickSight Test

.github/workflows/cfn-nag.yml
- Bugfix
- other github workflows as well as codebuild buildspecs are currently pinning poetry to version 1.1.15, updating cfn-nag workflow to be consistent
- do not remove poetry.lock
=> pin poetry to version 1.1.15 to avoid package resolution issues, do not remove lock file

awswrangler/s3/_read_text.py, tests/unit/test_s3_text.py
- Bugfix
In #1567, the ability to fetch a specific version of an S3 object was broken. The unit tests in that were meant to cover this use-case were not checking the code well enough, as they were only checking whether the most recent version had been pulled.
=> Fix: S3 read text with version ID was not working

test_infra/app.py, test_infra/poetry.lock, test_infra/pyproject.toml, test_infra/stacks/base_stack.py, test_infra/stacks/databases_stack.py
- Feature
- adding a Redshift Serverless workgroup and namespace - both are required to use Redshift Serverless
- Redshift Serverless uses its own secret in Secrets Manager. it cannot reuse the secret for Redshift as the content differs
- configuring the VPC to use 3 AZs instead of 2 as this is a requirement for Redshift Serverless
- this required adding account and region details to all stacks ([environment-agnostic stacks are limited to 2 AZs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Vpc.html#maxazs))
- #1530
=> Redshift Serverless test infrastructure

CONTRIBUTING_COMMON_ERRORS.md, test_infra/stacks/databases_stack.py
- Enhancement
- LakeFormation permissions for the CodeBuild test roles should be handled outside the public repository (i.e. in our internal test infra architecture). With this change, our users won't face the cryptic LF error at deployment anymore.
=> (enhancement): Remove unnecessary LF permissions from tests infra

awswrangler/s3/_write_parquet.py, awswrangler/s3/_write_text.py
- Refactoring
- Reduce LOC in S3 write methods create_table
=> (enhancement): Reduce LOC in S3 write methods create_table

.bumpversion.cfg, CONTRIBUTING.md, awswrangler/distributed/_distributed.py, awswrangler/distributed/_utils.py, awswrangler/distributed/datasources/pandas_text_datasource.py, awswrangler/distributed/datasources/parquet_datasource.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_write_dataset.py, poetry.lock, pyproject.toml, tests/load/test_s3.py, tutorials/034 - Distributing Calls on Ray Remote Cluster.ipynb
- Feature
- Update to Ray 2.0, Modin 0.14.1
- Use OOB Ray ParquetReader that now includes loading partitions as columns
- Update init logic to connect to the cluster if the address is provided or cluster is detected, or init local cluster otherwise
=> Upgrade to Ray 2.0

awswrangler/_config.py, awswrangler/distributed/_distributed.py, awswrangler/s3/_write_parquet.py
Ray does not always set `RAY_ADDRESS` environment variable that we use to detect a running cluster and connect to it. Adding `address` parameter back to be able to set conventional `WR_ADDRESS` and connect to a cluster instead of always creating a local cluster.
=> (fix): Return address config param

poetry.lock
- Bugfix
- poetry keeps complaining about the lock file when installing dependencies: 
> Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
=> regenerate poetry.lock with no update

tutorials/003 - Amazon S3.ipynb
- Bugfix
- couple of semicolons that shouldn't be there in S3 tutorial
=> [skip-ci] remove semicolon from python code eol in s3 tutorial

test_infra/stacks/databases_stack.py
Ensure consistency with other clusters and fewer issues when recreating the databases stack
- Bugfix
- RemovalPolicy.DESTROY for Redshift cluster
- RemovalPolicy.DESTROY for Neptune cluster
=> set redshift and neptune clusters removal policy to destroy

awswrangler/s3/_write_dataset.py
=> Improve bucketing series generation by casting only the required columns

awswrangler/athena/_read.py, tests/test_athena.py
- Bugfix
When the query result is empty, `awswrangler.athena.read_sql_query()` returns a list of strings that correspond to the column names instead of an empty DataFrame.
- https://github.com/aws/aws-sdk-pandas/issues/1683
=> Fix athena.read_sql_query for empty table and chunk size not returning an empty frame generator

awswrangler/distributed/ray/modin/s3/_write_dataset.py, tests/load/test_s3.py
When partitioning multi-block datasets, without block index in the prefix blocks overwrite each other. Test case TBC.
=> (fix) partition block overwriting

awswrangler/distributed/ray/_core.py
- Refactoring
- Remove local from ray.init call
=> Remove local from ray.init call

test_infra/stacks/databases_stack.py, test_infra/stacks/opensearch_stack.py
- Feature
- OpenSearch is following semver (contrary to ES) and AWS console does not list < 1.3 any longer, hence why I'm renaming the method to `_setup_opensearch_1`. I'm expecting OpenSearch 2 [to be available eventually](https://opensearch.org/blog/releases/2022/05/opensearch-2-0-is-now-available/) and when that is the case we can add `_setup_opensearch_2`.
- I've updated the Oracle engine version to `rds.OracleEngineVersion.VER_19`. We might prefer keeping a specific version but that is in line with what we do for SQL Server (`rds.SqlServerEngineVersion.VER_15`).
=> upgrade engine versions to match defaults from aws console

README.md, awswrangler/_data_types.py, awswrangler/_utils.py, awswrangler/distributed/ray/_register.py, awswrangler/distributed/ray/modin/_utils.py, awswrangler/s3/_select.py, awswrangler/timestream.py, tests/load/test_database.py, tests/unit/test_timestream.py
- Feature
- Refactoring
- Distribute timestream write with executor
In non-distributed case, DataFrame is split into smaller sub-dfs based on # of threads.
In distributed case, sub-dfs are obtained from ray object reference ids which are then submitted to the two ray remote methods (`_write_df` and `_write_batch`)
=> (perf): Distribute timestream write with executor

awswrangler/s3/_fs.py, awswrangler/s3/_read_text.py, tests/test_s3_text.py
- Bugfix
- `read_csv` chokes on encoding errors even when passing `encoding_errors='ignore'`. This happens due to ours casting the S3 object to `TextIOWrapper` after retrieving it and passing that to `pd.read_csv`.
- When specifying `encoding_errors='ignore'` we now keep the object as a set of bytes (`mode=rb`). In this case pandas is now responsible for wrapping this in a TextIOWrapper and deals with encoding and encoding errors.
I'm actually thinking we should never wrap the S3 object into a TextIOWrapper ourselves - as far as I can tell there is no advantage doing that and pandas will take care of it anyway. `mode` should always be set to `rb` in our code... but I'm curious about others' opinion!
- #1668
By submitting this pull request, I confirm that my contribution is made under the …
=> read_csv: read file as binary when encoding_errors is set to ignore

poetry.lock, pyproject.toml
- Remove upper bound limit on 'python' version
- #1714 
=> Deps: Remove upper bound limit on 'python' version

awswrangler/_config.py, awswrangler/_utils.py, tests/test_config.py
- Bug: Add correct service names for timestream boto3 clients
- Timestream boto3 client service names are [`timestream-query`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-query.html#client) and [`timestream-write`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#client) and our config method needs to expect those service names instead of `timestream`
- #1710 
=> Bug: Add correct service names for timestream boto3 clients

awswrangler/s3/_read_parquet.py, tests/test_s3_parquet.py
- Fixing index column validation in `s3.read.parquet()` validate schema.
- Add test case to validate the above.
- #1717 
=> Bug: Fixing index column validation in `s3.read.parquet()` validate schema

poetry.lock, pyproject.toml
`tqdm` progress bar should be opt-in instead of installed with ray extra by default. It's only required when a user expects to run the script and observe live output, otherwise it's polluting stderr.
=> (feat) Make tqdm progress reporting opt-in

awswrangler/distributed/ray/_register.py, awswrangler/s3/_describe.py, awswrangler/s3/_read.py
- Feature
- Distribute describe_objects S3 method with executor
=> (feat): Distribute describe_objects S3 method

awswrangler/emr.py
- Bugfix
- Replace `extra_registries` with `extra_public_registries` in `emr.py` to conform to the arguments. 
- https://github.com/aws/aws-sdk-pandas/issues/1755
=> Bug: Replace extra_registries with extra_public_registries

awswrangler/s3/_read_parquet.py
- Bugfix
This `read_parquet` documentation contained a few typos with examples using CSV not Parquet. It might come from copy pasting the original code template for `read_csv`
- https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet.html
=> typos in comments and docs

tests/unit/test_s3_parquet.py
- Bugfix
- Add xfail to `test_read_parquet_schema_validation_with_index_column` since `ignore_index` was removed
=> Add xfail to test_read_parquet_schema_validation_with_index_column

awswrangler/cloudwatch.py, docs/source/api.rst, tests/test_cloudwatch.py
- Feature
- Add `describe_log_streams` to CloudWatch module for getting log streams' details from specified log group.
- Add `filter_log_events` to CloudWatch module for returning filtered log events from specified log group's log streams.
=> Add describe_log_streams and filter_log_events to the CloudWatch module

awswrangler/athena/_read.py, awswrangler/athena/_utils.py, tests/test_athena.py
- Feature
- Support CTAS write_compression in wr.athena.read_sql_query
https://github.com/aws/aws-sdk-pandas/issues/1793
=> Add ctas_write_compression argument to athena.read_sql_query

awswrangler/distributed/ray/modin/_utils.py, tests/load/test_s3.py
- Bugfix
- Ray dataset with multiple empty blocks messes up resulting modin data frame
- #1783 
=> (fix) Distrib S3 Select - check row count before creating the Ray dataset

awswrangler/emr.py
- Feature
- Add `AutoTerminationPolicy` as an option for EMR cluster creation. This protects us from keeping a cluster alive while idle for a long time. 
- https://github.com/aws/aws-sdk-pandas/issues/1800
=> Add auto termination policy to EMR

awswrangler/timestream.py, tests/test_timestream.py
- Feature
- add QueryId and NextToken to pandas df attributes when chunked = True and pagination is used
- #1566
- #838
=> timestream.query: add QueryId and NextToken to df attributes

awswrangler/quicksight/_create.py
- `wr.quicksight.create_athena_dataset()`: Changing `sql_name` to optional variable with uuid
- Change `sql_name` to _optional_
- If `sql_name` is not specified use default from before `CustomSql` as a prefix and a uniquely generated id as a suffix to avoid the issues as discussed in #1511 
- #1511 
=> `wr.quicksight.create_athena_dataset()`: Changing `sql_name` to optional variable with uuid

awswrangler/distributed/ray/modin/_utils.py
Mypy typing fix for 
```
awswrangler/distributed/ray/modin/_utils.py:65: error: Returning Any from function declared to return "bool"  [no-any-return]
```
[FYI](https://github.com/python/mypy/issues/5697)
=> fix: Mypy `awswrangler/distributed/ray/modin/_utils`

awswrangler/timestream.py, tests/test_timestream.py
- Feature
- ability to pass boto3 arguments to timestream.create_table
- associated test case
- #1629
=> add support for boto3 kwargs to timestream.create_table

docs/source/conf.py
- With the latest aws sdk for pandas version we've lost color in the [tutorials](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/033%20-%20Amazon%20Neptune.html). Adding below [extension](https://nbsphinx.readthedocs.io/en/0.8.9/installation.html#Pygments-Lexer-for-Syntax-Highlighting) OR installing IPython from conda solves the issue.
=> (docs) Add extension for ipython console highlighting

awswrangler/_config.py, awswrangler/athena/_read.py, awswrangler/athena/_utils.py, awswrangler/exceptions.py, awswrangler/quicksight/_utils.py, awswrangler/redshift.py, awswrangler/s3/_download.py, awswrangler/s3/_fs.py, awswrangler/s3/_merge_upsert_table.py, awswrangler/s3/_upload.py
- Bugfix
- Refactoring
The definition for `apply_configs` so far has been `Callable[..., Any] -> Callable[..., Any]`. This means that IntelliSense as well as MyPy were not able to do check the types whenever a function decorated with `apply_configs` was called. Functions such as `wr.s3.to_parquet` were therefore treated as having a signature of `Callable[..., Any] -> Callable[..., Any]`.
By changing the definition of `apply_configs` to make use of generic types, MyPy was able to find errors related to inconsistent type usages (e.g. `Optional[str]` being passed as `str`). As such, I've had to fix all these type errors as part of this PR.
Furthermore, since making this change, the auto-complete in Visual Studio Code is now able to pick up types for functions such as `wr.s3.to_parquet` …
=> Fix apply_configs decorator causing function signature to be lost

awswrangler/data_quality/__init__.py, awswrangler/data_quality/_create.py, awswrangler/data_quality/_get.py, awswrangler/data_quality/_utils.py, docs/source/api.rst, tests/conftest.py, tests/test_data_quality.py
- Feature
- Refactoring
- Add recommendation and get APIs
- Add tests
- Refactor some methods in _utils
=> (feat): Add recommendation and get APIs

awswrangler/s3/_read_parquet.py
Bugfix
When reading parquets from S3 and using `validate_schema=True`, `use_threads` would always be set to `True`.
In practice this is not a big deal, but I found that 40% of the time my tests were taking was spent on waiting on locks for threading in `_validate_schemas_from_files`.
https://github.com/aws/aws-sdk-pandas/issues/1868
=> forward use_threads to _validate_schemas_from_files

tox.ini
=> Add coverage report to tox

awswrangler/_data_types.py, awswrangler/timestream.py, tests/test_timestream.py
- Bugfix
- Add datetime related data types to pyarrow2timestream conversion method
- Handle edge case of timestamp conversion
- Add test
- #1853
=> (fix): missing timestamp data type in Timestream

pyproject.toml
- Feature
- Remove `awswrangler.distributed` from coverage report
=> Remove `awswrangler.distributed` from coverage report

awswrangler/_data_types.py
- Bugfix
- None is not preserved when inferring strings
- #1880
=> (fix): Handle None in databases data types

awswrangler/athena/_utils.py, awswrangler/data_quality/_utils.py
- Enhancement
- Current polling delay (0.25s) is too short and causes throttling too often. Increasing to 1 s instead
=> (enhancement): Increase polling delay to 1 second

poetry.lock, pyproject.toml
- Update `wheel` 0.37.1 -> 0.38.1
- [Sec Vulnerability](https://github.com/advisories/GHSA-qwmp-2cf2-g9g6)
=> Deps: Update wheel 0.37.1 -> 0.38.1

pyproject.toml
- Enhancement
- Add coverage section to pyproject
- Methods in neptune/_utils.py are not public. As no test is referencing them, they are skewing the coverage 
=> Add coverage section to pyproject

awswrangler/dynamodb/__init__.py, awswrangler/dynamodb/_read.py, docs/source/api.rst, tests/conftest.py, tests/test_dynamodb.py
- Feature
- Add to DynamoDB module a new `read_items` function to handle read operations towards a given DynamoDB Table, returning the results as pandas DataFrame
- aws/aws-sdk-pandas/issues/1867
=> feat: add read_items to dynamodb module

tests/load/test_databases.py, tests/load/test_s3.py
- Lowering most benchmark times after assessment of sample set of recent test runs.
- Further refinement should be considered as we continue to incur data. (i.e. STD deviation based upper bounds to set less arbitrary `benchmark_time` values.
=> Adjust load test benchmark values

awswrangler/catalog/_create.py
Document the create_csv_table function's sensitivity to column order
- https://github.com/aws/aws-sdk-pandas/issues/1918
=> Document the create_csv_table function's sensitivity to column order

tests/test_s3_deltalake.py
- https://github.com/delta-io/delta-rs/issues/855
=> (tests) add workaround to enable deltalake to use AWS profile creds

test_infra/stacks/base_stack.py
- CB needs `iam:PassRole` permissions to Glue DQ role and it's manual process if the role name is dynamic
=> (tests) minor - add Glue DQ role name

tests/test_athena.py
Fixes below (only on Python 3.7):
```
create_ctas_table_args = mock_create_ctas_table.call_args.kwargs
>           create_ctas_table_args["compression"] = compression
E           TypeError: '_Call' object does not support item assignment
```
=> (test) minor - fix mock call args error on py37

awswrangler/s3/_write_text.py, tests/unit/test_s3_text.py
- Refactoring
Currently, `s3.to_parquet` and `s3.to_csv` return a dictionary containing the written paths along with the partition values. If the data was not written into partitions, the latter is empty.
Meanwhile, `s3.to_json` uses a different mechanism. If there are no partitions, the function returns a list. Otherwise, it returns the same dictionary as `s3.to_csv` and `s3.to_parquet`.
Since we are doing a major release, we are able to make a breaking change that will make this behavior consistent. In this PR, I've made `to_json` always return a dictionary. Alternatively, we can have `to_csv` and `to_parquet` have the same behavior as `to_json` currently has.
=> Unify return values for write json

awswrangler/dynamodb/__init__.py, awswrangler/dynamodb/_read.py, awswrangler/dynamodb/_utils.py, docs/source/api.rst, tests/test_dynamodb.py, tests/test_moto.py, tutorials/028 - DynamoDB.ipynb
- Breaking Change
- Use ExecuteStatement instead of Scan for DynamoDB `read_partiql`
- Add `execute_statement` method
- #1571
=> (Breaking Change): Use ExecuteStatement instead of Scan for DynamoDB read_partiql

awswrangler/_utils.py, awswrangler/distributed/ray/_register.py, awswrangler/dynamodb/_read.py, awswrangler/dynamodb/_utils.py, awswrangler/s3/_select.py, awswrangler/timestream.py, tests/unit/test_dynamodb.py
- Feature
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.ParallelScan
- Distribute DynamoDB Parallel Scan (both threads and Ray)
- This requires converting items to arrow tables first (because Ray dataset requires arrow table references)
=> (feat): Distribute DynamoDB Parallel Scan

awswrangler/_threading.py, awswrangler/_utils.py, awswrangler/athena/_utils.py, awswrangler/distributed/ray/_pool.py, awswrangler/distributed/ray/modin/_core.py, awswrangler/lakeformation/_utils.py, awswrangler/s3/_describe.py, awswrangler/s3/_fs.py, awswrangler/s3/_list.py, awswrangler/s3/_select.py
- Refactoring
- Added generics for the `try_it` and `map` functions. This will allow MyPy to take advantage of type hints even when we use those decorators
=> Improve decorators to leverage typing and stubs

awswrangler/_utils.py, awswrangler/dynamodb/_read.py, awswrangler/s3/_select.py, awswrangler/timestream.py, poetry.lock
- Fix
- Enhancement
- grpc has been causing [issues](https://github.com/ray-project/ray/issues/31729) in ray 2.2. Version 1.5.2 has been [yanked](https://github.com/grpc/grpc/issues/31885#issuecomment-1419855827). I have updated the poetry lock as a result
- While looking at ray [examples](https://docs.ray.io/en/latest/ray-core/patterns/too-fine-grained-tasks.html), I discovered that itertools.chain is preferred for flattening lists
=> (enhancement): Replace flatten_list with itertools.chain

awswrangler/distributed/ray/modin/s3/_read_parquet.py, awswrangler/distributed/ray/modin/s3/_read_text.py
- Feature
- Use [FastFileMetadataProvider](https://docs.ray.io/en/latest/_modules/ray/data/datasource/file_meta_provider.html#FastFileMetadataProvider) to skip directory paths expansion
- #1982 
=> (enhancement) Use fast file metadata provider

awswrangler/distributed/ray/datasources/__init__.py, awswrangler/distributed/ray/datasources/arrow_json_datasource.py, awswrangler/distributed/ray/modin/s3/_read_text.py
- Feature
- Add support for JSON PyArrow data source, which will only be available with the parameters `orient="records"` and `lines=True`. It will result in faster reading operations.
- The `test_s3_read_json_simple` load test execution time has decreased from 8 seconds to 5.5 seconds
- Writing JSON with Arrow is not supported, so this feature will only work for reading. In the Ray [json_datasource](https://docs.ray.io/en/latest/_modules/ray/data/datasource/json_datasource.html), the `write_block` function uses the Pandas writing function.
=> Distributed: Add support for JSON PyArrow data source

awswrangler/timestream.py
Solves #2018.
I'm a bit unsure about the format of these docs.
I just pasted in the link like `https://blah`, not markdown `[blah](https://blah)`, because I couldn't see any other pages doing that.
=> Document return value of timestream.write

awswrangler/_data_types.py
- Bugfix
- Add missing TIME type to pyarrow2redshift conversion method
- #2024
=> fix: Add missing TIME type to pyarrow2redshift conversion method

tests/unit/test_s3.py, tests/unit/test_s3_text.py
Tests started to fail because all new objects are now SSE encrypted ([from Jan 5?](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html)).
=> (test) Fix SSE default

awswrangler/distributed/ray/_register.py, awswrangler/distributed/ray/modin/s3/_read_parquet.py, awswrangler/distributed/ray/s3/__init__.py, awswrangler/distributed/ray/s3/_read_parquet.py, tests/unit/test_fs.py
- Feature
- Add distributed variant of the `_read_parquet_metadata_file` function based on the PyArrow file system
- This version of the schema read will be slightly faster than the previous version. For 2222 objects, the mean execution time of reading the file metadata was reduced from 135 seconds to 123 seconds
=> Add distributed variant of the `_read_parquet_metadata_file` function based on the PyArrow file system

awswrangler/_config.py, tox.ini
- Refactoring
- Add `loaded` and `default` parameters to config args
- These arguments have been implemented in the `release-3.0.0` branch but were missing from `main`
- This should fix the intermittent errors we're getting where `suppress_warnings` doesn't get reset after `wr.config.reset()` method is called
- <URL or Ticket>
=> Add loaded and default parameters to config args

tests/test_config.py, tests/test_moto.py, tox.ini
- Refactoring
- Replace manual assignments to `os.environ` with mocks
- Usages of `os.environ` are global and may have unpredictable impacts across multiple unit tests
=> Replace manual assignments of `os.environ` with mocks

awswrangler/athena/_read.py, awswrangler/redshift.py, awswrangler/s3/_read_parquet.py
- Correct documentation for `chunksize=True`
- #2086
=> Correct documentation for `chunksize=True`

awswrangler/distributed/ray/modin/s3/_write_text.py, tests/load/test_s3.py
- Refactoring
When `test_s3_delete_objects` and `test_wait_object_exists` are preparing a large list of objects for the load test, they are using versions of the `to_text` methods which output a warning like:
```
WARNING  awswrangler.distributed.ray.modin.s3._write_text:_write_text.py:121 PyArrow method unavailable, defaulting to Pandas I/O functions: File is in the json format. This will result in slower performance of the write operations.
```
Since this step is only about preparing a list of ~500 objects on S3, there is no reason to use these version of `to_csv` and `to_json`, as it results in the same warning message being outputted ~500 times. 
=> Reduce unnecessary log output for load tests

tests/load/test_s3_modin.py
- Testing
Add `test_modin_s3_read_parquet_many_files` as a pure-Ray comparison baseline for `test_s3_read_parquet_many_files`.
According to the comparison, the "regular" test scenario, where we don't try to validate the schema, gives approximately the same results for the test scenario. The 1000 files take 49 seconds to load with both `awswrangler` and Ray's `read_parquet` function. The bulk read using Ray's `read_bulk_parquet` function takes 12 seconds, in contrast with Wrangler's implementation which takes 14 seconds.
=> Add` test_modin_s3_read_parquet_many_files`

awswrangler/athena/_read.py, awswrangler/distributed/ray/modin/s3/_write_text.py, tests/load/test_s3.py, tests/unit/test_athena.py, tests/unit/test_athena_csv.py, tests/unit/test_athena_parquet.py, tests/unit/test_catalog.py, tests/unit/test_lakeformation.py, tests/unit/test_redshift.py, tests/unit/test_routines.py, tests/unit/test_s3_parquet.py, tests/unit/test_s3_text_compressed.py
=> chore: Clean up unit tests

awswrangler/timestream.py, tests/test_timestream.py
- Enhancement
- Add timestream common attributes
TimestreamWrite exposes a [CommonAttributes](https://docs.aws.amazon.com/timestream/latest/developerguide/API_WriteRecords.html#timestream-WriteRecords-request-CommonAttributes) argument which enables the user to supply attributes that are applied to all write operations. For instance common dimensions or measure names.
This has two benefits:
1. It reduces the size of the input data frame
2. It reduces the size of the payload for each write call and thus reduces the cost
Introducing this argument means that other arguments must become optional (`time_col`, `measure_col`, `dimension_cols`...) because they can be supplied via the common_attributes instead
- closes #2082
By submitting this pull request, I confirm that my contribution is made …
=> enhancement: Add timestream common attributes

tests/conftest.py, tests/unit/test_redshift.py
- Chore
- Wrap redshift connectors in `with` block
- Also added type annotations for the Redshift unit tests
=> Unit tests: Wrap redshift connectors in `with` block

poetry.lock, pyproject.toml, tox.ini
- `gremlinpython` pulls versions of `aiohttp` that fail to build on `3.11`, but since in `release-3.0.0` gremlin is an optional dependency, nothing prevents us from supporting `3.11`.
- We'll be able to support 3.11 in main after `gremlinpython==3.6.3` is released (rc available).
=> enhancement: Allow Python 3.11

awswrangler/catalog/_create.py, tests/test_s3_parquet.py, tests/test_s3_text.py
- Refactoring
- `to_csv` and `to_json` did not support schema evolution the way that `to_parquet` does
- https://github.com/aws/aws-sdk-pandas/issues/2103
=> fix: Schema evolution for `to_csv` and `to_json`

tests/conftest.py, tests/load/test_s3.py, tests/load/test_s3_modin.py
- Enhancement
- Replace load tests bucket with SSM parameter
=> tests: Replace load tests bucket with SSM parameter

pyproject.toml
Pandas 1.5.0 had a memory leak with awswrangler,
but according to https://github.com/aws/aws-sdk-pandas/issues/1678 it is no longer the case.
The current dependency expressed in pyproject.toml locks dependents to use only 1.5.1. Since the bug has been fixed in pandas we can now remove the lock.
- Bugfix
- awswranger does not let people use pandas 1.5.2+
- https://github.com/aws/aws-sdk-pandas/issues/1678
=> fix: remove constrain on pandas 1.5+

awswrangler/s3/_wait.py, tests/load/test_s3.py
- Refactoring
- Replace usage of the `parallelism` argument with `use_threads`, as we do elsewhere in the codebase (e.g. `wr.dynamodb.read_items`)
=> chore: Remove `parallelism` parameter from S3 wait methods

awswrangler/_distributed.py, awswrangler/distributed/ray/modin/s3/_write_dataset.py, awswrangler/s3/_write.py, docs/source/scale.rst, validate.sh
- Refactoring
- Fix line-too-long errors in `about.rst` which have been causing static check errors
- Clarify return type of `_sanitize` function. A named tuple will make it clearer what each of the 4 values in the tuple represents
- Add string literals for engine and memory format specification.
=> chore: Typing improvements

docs/source/_templates/typed-dict-template.rst, docs/source/api.rst
- Add the TypedDict classes from `awswrangler.typing` into the docs
- I had to create a new template in order to properly display the `TypedDict`.
=> chore: Add typeddicts to docs

awswrangler/cloudwatch.py
- Bugfix
- The default value for the `end_time` parameter is currently defined as `datetime.datetime.utcnow()`. However, this is evaluated at import time not at run time. With this change, `end_time` will be set to `None` by default and thus evaluated as `utcnow()` at run time.
- Fixes #2185
=> fix: Fix default `utcnow` argument in `start_query`

poetry.lock, pyproject.toml
Modin `0.20.0` (and Ray `2.3.1` micro upgrade) are released. Bumping versions in `poetry.lock`.
=> dependencies: Upgrade Modin to 0.20.0

awswrangler/_data_types.py, awswrangler/pandas/__init__.py, poetry.lock, pyproject.toml, tests/_utils.py, tests/unit/test_athena.py, tests/unit/test_data_quality.py, tests/unit/test_s3_text.py
NOTE: This PR only allows to install the library with Pandas 2.x as requested by some users. It does not add full Pandas 2.x internal support such as using pyarrow types. This will be addressed in the next PRs.
- Allow Pandas 2.x (note Modin still requires `1.5.3` so that's what the lock file pulls)
- Minor test fixes (renamed parameters, deprecated df.append())
- Minor extension types update
- #2200 
=> dependencies: Allow Pandas 2.x

README.md, docs/source/index.rst
- Fix links to 'Who uses library' section
=> docs: Fix links to 'Who uses library' section

tests/unit/test_redshift.py, tox.ini
- Bugfix
- Fixing `test_spectrum_decimal_cast` test. It was failing due to an issue where the indices for both rows in the Frame were 0 when running in distributed mode.
=> fix: Fixing `test_spectrum_decimal_cast` test

tox.ini
- Bugfix
- Tox wasn't installing versions of dependencies from `poetry.lock`. The script therefore updated from PyArrow 11 to PyArrow 12 behind the scenes, causing issues with index recovery.
=> fix: Tox environment dependency issues

awswrangler/timestream/_write.py, tests/unit/test_timestream.py
- Feature
Current timestream write API is limited to MILLISECONDS precision only. This PR attempts to enable other time units (SECONDS, MICROSECONDS and NANOSECONDS).
One remaining issue is how to handle NANOSECONDS precision. `datetime` python objects are limited to microseconds precision so we would not be able to handle that.
- Allow `time_unit` parameter to write method
- #2261
=> feat: add time unit to timestream write API

awswrangler/distributed/ray/modin/s3/_read_parquet.py, tests/unit/test_s3_parquet.py
- Hotfix to avoid OOMs when computing index for multi-file distributed datasets
=> fix: Ignore index for multi-file datasets in distributed mode

awswrangler/distributed/ray/modin/s3/_read_parquet.py, tests/unit/test_s3_parquet.py
Reverts aws/aws-sdk-pandas#2266
=> Revert "fix: Ignore index for multi-file datasets in distributed mode"

tests/unit/test_redshift.py
- Bugfix
Fix recurring issue with `test_spectrum_decimal_cast`. The problem was that after filtering out the frame:
```python
df2 = df2[df2.c0 != 2]
```
we were trying to access the element with the index value `0`
```python
assert df2.c1[0] == Decimal("1.00000")
```
The filtering does not remove the index of each row. Since the data gets shuffled by the Athena query, there's a 50% chance that the value we want to access still has an index of `1`.
I resolved the issue by simply resetting the index of the filtered data frame, so that the only element in it will always have an index of `0`.
=> fix: Recurring issue with `test_spectrum_decimal_cast`

awswrangler/redshift/_read.py, tests/unit/test_redshift.py
- Bugfix
`redshift.unload_to_files` wasn't escaping SQL query. As such, the user has had to escape the SQL query themselves when querying a string value.
- Closes #1116
=> fix: Redshift unload not escaping SQL query

awswrangler/_arrow.py, awswrangler/_data_types.py, awswrangler/_databases.py, awswrangler/athena/_read.py, awswrangler/athena/_utils.py, awswrangler/data_api/_connector.py, awswrangler/data_api/rds.py, awswrangler/data_api/redshift.py, awswrangler/dynamodb/_utils.py, awswrangler/neptune/_gremlin_parser.py, awswrangler/neptune/_neptune.py, awswrangler/opensearch/_write.py, awswrangler/oracle.py, awswrangler/s3/_read.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_write_dataset.py, pyproject.toml, validate.sh
- Bugfix
- Fix Ruff formatting errors
=> fix: Ruff formatting errors

awswrangler/opensearch/_write.py, tests/unit/test_opensearch.py
- Feature
- Implement parallel bulk
- Off (no threads) by default to avoid introducing breaking changes for the users
- Note parallel bulk does not support a few minority parameters: max_retries, initial_backoff & max_backoff. Whether to require user to explicitly set those to None (as they have defaults in regular bulk) in order to be able to use parallel bulk is open for discussion.
- #1968 
=> feat: Opensearch parallel bulk

awswrangler/_distributed.py
- Bugfix
Engine initialization did not respect OS env. When importing `awswrangler`, `engine.register` gets called. This function looks at only the value of the `name` parameter (`None` in this case) or the output of `engine.get_installed()`.
=> fix: Engine initialization did not respect OS env

awswrangler/athena/__init__.py, awswrangler/athena/_spark.py, awswrangler/exceptions.py, docs/source/api.rst, test_infra/stacks/base_stack.py, tests/unit/test_athena_spark.py, tutorials/041 - Apache Spark on Amazon Athena.ipynb
- Feature
- This PR adds basic capabilities to start a session and kick off a calculation. Any potential data integration (i.e. ability to pass data frames, read results) will be addressed in next PRs.
- Add `create_spark_session` and `run_spark_calculation` with corresponding waiters
- Add simple test case
- Expand test case
- Add tutorial / docstrings
- Add test infra IAM role
=> feat: Apache Spark on Amazon Athena - `wr.athena.create_spark_session` & `wr.athena.run_spark_calculation`

.github/workflows/static-checking.yml, poetry.lock, validate.sh
- Add static checking of `poetry.lock` consistency with `pyproject.toml`
=> chore: Add static checking of poetry.lock consistency with pyproject.toml

awswrangler/cleanrooms/_read.py
- Bugfix
- Boto3 session not being passed to `cleanrooms.wait_query` from `cleanrooms.read_sql_query`
- #2380
=> fix: Boto3 session not being passed to `cleanrooms.wait_query`

awswrangler/s3/_write.py
- Bugfix
AWS Glue enforces sanitisation of table and column names. For instance, a table with name `Metadata` would be automatically sanitised to `metadata` (i.e. lowercase) at creation.
However, this behaviour does not seem to apply to nested fields in data type values. The `CreateTime` value in the `struct<CreateTime:timestamp, LastUpdatedTime:timestamp>` data type is not sanitised by the service.
See #2357  for more details.
My worry is whether we wouldn't be breaking something else with this change?
- Avoid lowercasing `dtype` data type values in `to_parquet` sanitisation process
- #2357
=> fix: remove .lower in dtype sanitize for to_parquet

awswrangler/postgresql.py
- Feature
- Use `pg8000.native.identifier()` and `literal()` to validate and escape table identifiers
=> feat: PostgreSql improvements - escape and validate table identifiers and literals

awswrangler/s3/_read_parquet.py, tests/unit/test_s3_parquet.py
- Bugfix
- Passing the schema allows to avoid `StopIteration` in pyarrow's `pa.Table.from_batches(chunks)` when reading files with no rows. This will create an empty table using the schema and loading partition columns.
- https://github.com/aws/aws-sdk-pandas/issues/2394
=> fix: Pass schema to chunked parquet reads

awswrangler/dynamodb/_read.py, tests/unit/test_dynamodb.py
Signed-off-by: Abdel Jaidi <jaidisido@gmail.com>
- Bugfix
- Support pyarrow schema in DynamoDB read_items
- #2399
=> fix: support pyarrow schema in DynamoDB read_items #2399

awswrangler/distributed/ray/_executor.py, awswrangler/distributed/ray/_utils.py, awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py, awswrangler/s3/_read_deltalake.py, poetry.lock, pyproject.toml, tests/unit/test_athena.py, tests/unit/test_athena_csv.py, tests/unit/test_athena_parquet.py, tests/unit/test_s3_parquet.py, tests/unit/test_s3_select.py, tests/unit/test_s3_text.py, tox.ini
Signed-off-by: Abdel Jaidi <jaidisido@gmail.com>
- Dependencies
- upgrade Ray to 2.6 and fix security dependabots
=> ci: upgrade Ray to 2.6 and fix security dependabots

awswrangler/distributed/ray/modin/_utils.py, tests/unit/test_s3_select.py
- Bugfix
- use `from_arrow` instead of `from_arrow_refs`
- https://github.com/ray-project/ray/issues/37928
=> fix: use from_arrow instead of from_arrow_refs

building/lambda/build-lambda-layer.sh
- Bugfix
- Deleting libarrow.so files is causing lambda layer to fail. The deletion was initially put in place to save space but is not longer needed
- https://github.com/apache/arrow/pull/7334
=> fix: prevent lambda build from deleting libarrow files

.github/dependabot.yml
Signed-off-by: Abdel Jaidi <jaidisido@gmail.com>
- Feature
Dependabot now supports grouped pull requests:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
A single pull request per group is opened, updating multiple packages at once. As a result, there is no need to skip the CI anymore
Note that the feature is in beta
=> feat: test dependabot groups feature

awswrangler/s3/_write_parquet.py
- Bugfix
- <feature1 or bug1>
- https://github.com/aws/aws-sdk-pandas/issues/2454
=> fix: Duplicate schema argument in `wr.s3.to_parquet()`

tests/glue_scripts/wrangler_blog_simple.py, tests/load/test_databases.py, tests/load/test_s3.py
- Bugfix
- `amazon-reviews-pd` bucket is no more. Using `ursa-labs` instead
=> fix: replace amazon-reviews with ursa-labs public S3 bucket

awswrangler/catalog/_create.py, tests/unit/test_catalog.py
- Bugfix
- Add missing call to `sanitize_column_name` in `create_*_table`
- This fixes an issue where column comments are not applied if the column name is not sanitized
- #2463
=> fix: Add missing call to `sanitize_column_name` in `create_*_table`

awswrangler/athena/_write_iceberg.py, tests/conftest.py, tests/unit/test_athena.py
- Feature
- The `athena.to_iceberg` function does not work for a hyphenated table name
=> fix: Hyphenated Iceberg table names

awswrangler/opensearch/_utils.py
- Bugfix
- Fails to import in projects where `opensearch-py` is installed, but not the `awswrangler[opensearch]` module
- #2470
=> fix: `requests_aws4auth` not being treated as an optional dependency

awswrangler/data_api/redshift.py, tests/unit/test_data_api.py
- Feature
- Allow all combinations of auth as per https://docs.aws.amazon.com/redshift/latest/mgmt/data-api-access.html
- https://github.com/aws/aws-sdk-pandas/issues/2435
=> feat: Redshift data api - allow all auth combinations

awswrangler/athena/_cache.py
- Bugfix
- When updating cache in Athena `read_sql_query` code flow on a multi thread code we got an KeyError exception.  Now have updated code to only remove the item in cache if key actually exists.
=> fix: KeyError exception in athena wrangler

.readthedocs.yml
- Feature
- Our documentation is no longer building because we didn't perform [this migration](https://blog.readthedocs.com/use-build-os-config/) in time
- Added the missing `build.os` variable
- We are currently missing the documentation for release `3.4.1` because it's failing to build
=> fix: readthedocs failing because of missing build.os variable

.readthedocs.yml
- Feature
- Our documentation is no longer building because we didn't perform [this migration](https://blog.readthedocs.com/use-build-os-config/) in time
- Added the missing `build.os` and `build.tools` variables
- We are currently missing the documentation for release `3.4.1` because it's failing to build
=> fix: readthedocs migration

awswrangler/data_api/rds.py, awswrangler/mysql.py, awswrangler/sqlserver.py
- Bugfix
- Add parameterized queries where possible to address the risk of SQL injection
=> fix: Add parameterized queries where possible to address the risk of SQL injection

awswrangler/s3/_write_parquet.py, tests/unit/test_data_quality.py
- Bugfix
Currently by default we coerce timestamps to `ms`. According to pyarrow, valid values are `{None, ‘ms’, ‘us’}`. If `None` is given, the defaults are chosen based on Parquet version (1.0 and 2.4 use microseconds, while for others timestamps are written natively w/o loss of resolution). We should allow `None`.
- Slack thread
=> fix: coerce_timestamps - allow None

awswrangler/redshift/_read.py, awswrangler/redshift/_utils.py
- Refactoring
- Add validation for `table` and `schema` parameters for Redshift
=> fix: Add validation for `table` and `schema` params for Redshift

tests/_utils.py, tests/unit/test_s3_select.py, tests/unit/test_s3_text_compressed.py
- Add `xfail` to unit tests failing because `index=False` and `orient="records"` have been set on a version of Pandas that doesn't support this.
=> fix: Python 3.8 unit tests

poetry.lock, pyproject.toml
- Set minimun aiohttp version to address [CVE-2023-49082](https://nvd.nist.gov/vuln/detail/CVE-2023-49082).
- Gremlin made some of the dependencies (including transport) optional thus adding aiohttp as a direct dependency.
- Also bumping gremlin to the latest version.
=> chore: Update gremlinpython & add aiohttp

poetry.lock, pyproject.toml
- Bugfix
- Adding missing `async-timeout` dependency
=> fix: Gremlin throwing import error on Python 3.11 and 3.12

awswrangler/dynamodb/_read.py, awswrangler/dynamodb/_utils.py, tests/unit/test_dynamodb.py
- Bugfix
- Fix deserialization error when reading from DynamoDB using `KeyConditionExpression`
- Added unit tests to make sure the output has been deserialized for all the different read options in the DynamoDB module
- Upgraded unit tests to check for DataFrame equality
- #2605
=> fix: Deserialization error when reading from DynamoDB using `KeyConditionExpression`

docs/source/api.rst
- Feature
- adds `show_create_table` to  docs for Athena
- <URL or Ticket>
=> docs: add show_create_table to athena api ref

awswrangler/dynamodb/_read.py, tests/unit/test_dynamodb.py
- Bugfix
- DynamoDB Key and Filter expressions end up overwriting each other.
- https://github.com/aws/aws-sdk-pandas/issues/2614
=> fix: DynamoDB key & filter expressions attribute overwrite

.github/dependabot.yml
- Adding dependabot configuration to update the versions of the GitHub actions that we use
- I tested this out in a fork repo, and this is what the update PR would look like: https://github.com/LeonLuttenberger/aws-sdk-pandas/pull/7
=> chore: Upgrade dependabot to upgrade GitHub actions

awswrangler/postgresql.py, tests/conftest.py, tests/unit/test_postgresql.py
- Bugfix
- Fix postgres reserved keywords not getting escaped when used as column names
- The `pg8000.native.identifier` method we've used to escape literals doesn't take reserved keywords into account when deciding when a literal needs to be wrapped in quotation marks. Instead, we'll be using our own method, which will wrap the literal into quotation marks no matter what.
- #2617
=> fix: PostgreSQL reserved keywords as column names

awswrangler/_data_types.py, awswrangler/s3/_read.py
- Bugfix
- Remove unused code that was referring to a type that was removed in Pyarrow 15
- https://github.com/aws/aws-sdk-pandas/issues/2633
=> fix: Pyarrow 15 imports & remove unused code

docs/source/conf.py, poetry.lock, pyproject.toml
- Upgrade ruff to `0.2.0` and fix warnings in pyproject.toml
=> chore: Upgrade ruff to 0.2.0

awswrangler/_data_types.py
- Bugfix
- Adds support for the pyarrow `large_string` datatype when converting from pyarrow to all supported storage backends
- Consider this a draft PR, there may be more changes required, extension of tests etc.
- Fixes #2662 
=> fix: Add support for pyarrow type large_string

awswrangler/s3/_read_excel.py, awswrangler/s3/_write_excel.py
- Bugfix
- Remove enforced openpyxl engine constraint
- #2695 
=> fix: remove enforced openpyxl engine constraint

awswrangler/athena/_read.py
- Bugfix
- Fix indentation for categories in `_fetch_parquet_result`. As it's currently setup, `categories` is never passed if `pyarrow_additional_kwargs` is passed by the user
- #2700
=> fix: indent categories in pyarrow_additional_kwargs correctly

awswrangler/redshift/_write.py
- fix `redshift.to_sql` doc indentation error
- #2704
=> docs: fix `redshift.to_sql` doc indentation error

building/lambda/Dockerfile, building/lambda/Dockerfile.al2023
Currently, we are unable to build our layers due to this issue in PyArrow: https://github.com/apache/arrow/issues/40375
Pinning Cython to an earlier version as a workaround.
=> fix: Pin Cython version to workaround issue when building PyArrow from source

tests/unit/test_athena.py, tox.ini
- Adding the `max_results` parameter to any tests using `athena.list_query_executions`
- Without this parameter, the tests using the `list_query_executions` function are taking a long time to execute, as the function will list every single Athena execution in the workgroup.
- Configure `pytest` so that it only queues up two tests for each worker
- This is to prevent a single worker from ending up with a long queue of long running unit tests. For example, a single worker would wind up with a queue of all the test for OpenSearch, each of which takes 20-30 seconds to execute. This practically eliminated any gains from parallelizing our unit tests.
Our distributed tests should now take 40-45 minutes, down from over an hour. The non-distributed ones are down to 16 minutes, although this is …
=> test: Reduce execution time for the unit tests

awswrangler/athena/_write_iceberg.py, tests/unit/test_athena_iceberg.py
- Bugfix
- Allow passing `s3_output` in athena.to_iceberg
- #2710
=> fix: allow s3_output in athena.to_iceberg

awswrangler/athena/_write_iceberg.py, tests/unit/test_athena_iceberg.py
- Bugfix
- fix Athena `to_iceberg` failing with non-lowercase column names
- #2734
=> fix: Athena to_iceberg fails with non-lowercase column names

awswrangler/_data_types.py, tests/unit/test_athena_iceberg.py
- Bugfix
- Iceberg schema evolution fails for map, array, and struct types
=> fix: Iceberg schema evolution fails for map, array and struct types

tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb
- The YAML in the Ray Remote tutorial is not displayed properly [in the documentation](https://aws-sdk-pandas.readthedocs.io/en/3.7.2/tutorials/035%20-%20Distributing%20Calls%20on%20Ray%20Remote%20Cluster.html#Configure-Ray-Cluster-Configuration)
=> docs: Fix YAML formatting in Ray Remote tutorial

awswrangler/opensearch/_write.py
- Bugfix
- Remove redundant `_id` generation as it is generated by OpenSearch by default.
- Additionally, passing `_id` is [not supported](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-genref.html#serverless-operations)  by OpenSearch **vector search** collections (see PUT `<index>/_create/<id>` (for search collection types only):
```
opensearchpy.helpers.errors.BulkIndexError: ('3 document(s) failed to index.', [{'index': {'_index': 'dummy-vector-search-1', '_id': '32300c88-a52c-4a14-95f6-aad4919b1b7b', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'Document ID is not supported in create/index operation request'}, 'data': {'name': 'John'}}}, {'index': {'_index': 'dummy-vector-search-1', '_id': …
```
=> fix: Opensearch serverless vector search collections - remove default `_id`

awswrangler/athena/_read.py, awswrangler/athena/_utils.py, tests/unit/test_athena.py
- Feature
- Support client-side parameter resolution in athena.create_ctas_table
- #2787
=> feat: Support client-side parameter resolution in athena.create_ctas_table

awswrangler/postgresql.py
- Feature
- add `commit_transaction` to postgres.to_sql
- closes #2790
=> feat: add commit_transaction to postgres.to_sql

awswrangler/_data_types.py, tests/unit/test_athena.py
- Bugfix
- https://github.com/aws/aws-sdk-pandas/issues/2794
=> fix: Support json type in athena2pandas

awswrangler/postgresql.py, tests/unit/test_postgresql.py
- Feature
- add overwrite_method to `postgresql.to_sql`
- #2728
=> feat: add overwrite_method to `postgresql.to_sql`

awswrangler/athena/_statements.py, awswrangler/postgresql.py, awswrangler/redshift/_write.py, awswrangler/s3/_copy.py
- Bugfix
Fix enumerations in doc pages:
1. [awswrangler.postgresql.to_sql](https://aws-sdk-pandas.readthedocs.io/en/3.7.3/stubs/awswrangler.postgresql.to_sql.html)
2. [awswrangler.redshift.to_sql](https://aws-sdk-pandas.readthedocs.io/en/3.7.3/stubs/awswrangler.redshift.to_sql.html#awswrangler.redshift.to_sql)
=> docs: Fix enumerations in doc pages

docs/environment.yml
- Bugfix
- Fix readthedocs errors by pinning sphinx version
=> docs: Fix readthedocs errors by pinning sphinx version

awswrangler/athena/_write_iceberg.py
- Feature
- add `s3_output` parameter to `athena.delete_from_iceberg_table`
- #2828
=> fix: add `s3_output` parameter to `athena.delete_from_iceberg_table`

awswrangler/sqlserver.py, tests/unit/test_sqlserver.py
- Feature
Detail
- Adds upsert mode to sqlserver.py to_sql method
- Adds unit test to test the feature
=> feat: add upsert mode to sqlserver.py and corresponding tests

awswrangler/s3/_read.py, tests/unit/test_s3_parquet.py
- Bugfix
- `wr.s3.read_parquet_metadata` not throwing proper error for empty path
- #2842
=> fix: s3.read_parquet_metadata not throwing proper error for empty path

awswrangler/athena/_write_iceberg.py, tests/unit/test_athena_iceberg.py
- Feature
Sometimes, when inserting new data into an iceberg table it may be necessary to ignore existing data on some fields and load only the new ones, to avoid having unwanted overwrites on all columns of the dataset. 
In this case a check has been added on the type of merge you want to do, by default an update is done, or you can choose to ignore duplicate entries and go into insert with only the new ones.
Use case:
```
df1:
| title   |   year |    gross |
|:--------|-------:|---------:|
| Dune    |   1984 | 35000000 |
| Fargo   |   1996 | 60000000 |
```
```
df2:
| title   |   year |     gross |
|:--------|-------:|----------:|
| Dune    |   2021 | 400000000 |
| Fargo   |   1996 |  60000001 |
```
```
case 1: UPDATE (default)
wr.athena.to_iceberg(..., merge_cols=["title", "year"])
out: …
```
=> feat: Support different merge conditions in `athena.to_iceberg` function

awswrangler/athena/_spark.py
https://docs.aws.amazon.com/athena/latest/APIReference/API_StartSession.html#athena-StartSession-request-NotebookVersion, this parameter is necessary to create session using Spark
- Bugfix
Functions called from library
- run_spark_calculation
- create_spark_session
Missing Parameter for starting Session on Boto3.
After calling those two function this error is being raised:
InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartSession operation: NotebookVersion is required when NotebookId is provided.
- (https://docs.aws.amazon.com/athena/latest/APIReference/API_StartSession.html#athena-StartSession-request-NotebookVersion)
=> fix: Adding NotebookVersion Parameter as specified in official AWS Docs

awswrangler/athena/_write_iceberg.py, tests/unit/test_athena_iceberg.py
- Feature
When performing a merge operation between two Iceberg tables on Athena, join fields that contain NULL values do not 
match with corresponding NULL values in the other table. This issue is due to the generic behavior in SQL where NULL != NULL. As a result, rows with NULL values in the join columns fail to find matches, causing incomplete merges and data inconsistencies.
This pull request implement this feature by extending the join condition to account for NULL values. The enhanced join condition ensures that rows with NULL values in the join columns are correctly matched with corresponding rows in the other table that also have NULL values. 
The following example illustrates the differences between join condition:
- join condition that doesn't handle null values
```
MERGE INTO …
```
=> feat: manage `NULL` values in `athena.to_iceberg` merge statement

awswrangler/athena/_executions.py, awswrangler/athena/_read.py, awswrangler/athena/_utils.py
- Refactoring
- Align the default value of athena_query_wait_polling_delay in doc strings with the used constant
=> docs: fix default value in doc string for athena_query_wait_polling_delay parameters

awswrangler/_data_types.py, tests/_utils.py, tests/unit/test_pandas_pyarrow_dtype_backend.py
- Bugfix
- `athena.read_sql_query` with pyarrow backend trims time in timestamp
- #2874
=> fix: pyarrow backend trimming timestamp to date

awswrangler/_data_types.py, tests/unit/test_athena.py
- Bugfix
- fix `athena.read_sql_query` failing for time columns
- #2893
=> fix: athena.read_sql_query failing for time columns

docs/source/install.rst
Feature
The current install instructions for AWS Glue Python Shell Jobs are lacking. They only describe the more complicated solution of Using an Whl file. However, with Python 3.9 jobs, it's much easier to leverage pip for the install. Consequently, I added this to the documentation.
=> docs: Add steps to install "using pip" to the "AWS Glue Python Shell Jobs" part of the install docs

awswrangler/_utils.py, awswrangler/opensearch/_read.py, awswrangler/opensearch/_write.py
If a customer has `opensearchpy` installed but not `jsonpath_ng`, the import of awswrangler will fail. This goes against our current protocol, which is that we throw an appropriate import error when the customer tries to invoke a method which requires an optional dependency.
The `jsonpath_ng` dependency is also only required for certain cases when loading JSON data, so I'm only appending the annotation to the `_get_documents_w_json_path` function.
#2938
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
=> fix: OpenSearch import errors

awswrangler/_arrow.py, awswrangler/_data_types.py, tests/unit/test_s3_parquet.py
- Bugfix
Fixing a bug of failing to save a dataframe to parquet files, when the range of the timestamp is outside of the bounds of pyarrows Timestamp[ns]. With this fix the new supported time units (and thus the ranges), are:  ‘s’ [second], ‘ms’ [millisecond], ‘us’ [microsecond], or ‘ns’ [nanosecond] , based on https://arrow.apache.org/docs/python/generated/pyarrow.timestamp.html . 
Any other dataframe type will be defaulted to timestamp[ns], similar to current behaviour.
Bug fix for: https://github.com/aws/aws-sdk-pandas/issues/2950
=> fix(athena): Enable use of dataframe type, in athena2pyarrow type

awswrangler/redshift/_utils.py, awswrangler/redshift/_write.py, tests/unit/test_redshift.py
- Feature
I would like to propose a new feature for the Redshift table write methods.
Currently, if there's a columns mismatch between the input DataFrame and the target Redshift table, the write methods generate an exception. 
I propose adding an option to automatically handle this scenario by creating new columns in the Redshift table if they are present in the input DataFrame but missing in the table schema.
Specifically, I suggest introducing an additional argument like `add_new_columns: bool = False` to `_utils._create_table ` method.
If `True` and if new columns are found comparing input DataFrame and target table columns, it will automatically execute an `ALTER TABLE ADD COLUMN` on the target table.
This enhancement would align with the existing behavior of the `s3.to_parquet` …
=> feat(redshift): Automatically add new DataFrame columns to Redshift tables during write operation

awswrangler/_config.py
- Bugfix
Handling the special case where `WR_` environment variables are read as str but are intended as bool. This is similar to how we currently handle null values.
- #2965
=> fix: handle case of str to bool env variable in config

awswrangler/_data_types.py, awswrangler/_databases.py, tests/unit/test_postgresql.py
- Bugfix
- support postgresql array types
- https://github.com/aws/aws-sdk-pandas/issues/2964
=> fix: support postgresql array types

awswrangler/athena/_write_iceberg.py, awswrangler/catalog/_get.py, awswrangler/catalog/_utils.py, tests/unit/test_athena_iceberg.py
- Bugfix
- `wr.catalog.get_table_types` returns all columns including Iceberg columns that have been removed from the schema (and are marked with `iceberg.field.current: false`) that confuses subsequent `wr.athena.to_iceberg` `INSERT's`.
- https://github.com/aws/aws-sdk-pandas/issues/2978
- https://github.com/apache/iceberg/issues/7584
=> fix: return only "current" iceberg columns

awswrangler/opensearch/_write.py
- Feature
add `modify_refresh_interval` argument to opensearch's `index_documents()`
when set to `False` it won't try to modify refresh interval.
This argument is needed to be set to `False` if multiple workers write to the same index, which might disable refresh-interval due to race condition.
it's also possible that the backend role is not allowed to modify index settings (`indices:admin/settings/update`)
=> feat: modify_refresh_interval flag in opensearch index_documents

awswrangler/s3/_fs.py
- Bugfix
During a call to s3.to_parquet(), if the size of the data exceeds 5MB a multi-part upload operation will be initiated.
If the S3 call to CreateMultipartUpload fails (such as with a 503 SlowDown error) then the incomplete Parquet file data was being written to S3 using 'put_object' during close(). This resulted in broken Parquet files in S3, causing errors when queried by services like Athena.
Now, the data buffer is cleared at the end of the call to flush() -- even when an exception occurs.
https://github.com/aws/aws-sdk-pandas/issues/2987
=> fix: Prevent truncated Parquet files in S3 after failed CreateMultipartUpload (2987)

awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
- Bugfix
- remove _default_metadata_provider as it's not supported in ray 2.38.0+
- #3004
=> fix: remove _default_metadata_providers

tutorials/001 - Introduction.ipynb
- Bugfix
Small PR - fixes the `aws-sdk-pandas` and `pandas` repo links.
=> fix: update references in introduction notebook

awswrangler/s3/_read_parquet.py
- Bugfix
Fixes the read_parquet function in chunked mode. Currently a whole file gets loaded into the memory instead of row groups. This can lead to memory issues. 
- https://github.com/aws/aws-sdk-pandas/issues/3010
=> fix: read parquet file in chunked mode per row group

awswrangler/opensearch/_read.py, tests/unit/test_opensearch.py
- Feature
- return opensearch aggregation hits
- https://github.com/aws/aws-sdk-pandas/issues/3054
=> feat: return opensearch aggregation top hits

building/lambda/build-lambda-layer.sh
- Now that python 3.8 is deprecated, we can upgrade lambda layers to numpy 2.x.
=> chore: unpin numpy in lambda layers (allow numpy 2.x)

awswrangler/_data_types.py
- Bugfix
- Adds support for pyarrow's `large_list` to supported storage backends
- #3085 
=> fix: Supports pyarrow's `large_list`

tests/unit/test_s3_parquet.py
- Refactoring
- Adds unit test for testing pyarrow's `large_list` and `large_string` in `read_parquet_metadata`
- https://github.com/aws/aws-sdk-pandas/pull/3086
=> fix: `large_list` and `large_string` unit test for `read_parquet_metadata`

awswrangler/athena/_write_iceberg.py, tests/unit/test_athena_iceberg.py
- Feature
- Add pyarrow_additional_kwargs to athena.to_iceberg
- #3080
=> feat: add pyarrow_additional_kwargs to athena.to_iceberg

awswrangler/athena/_write_iceberg.py, tests/unit/test_athena_iceberg.py
- Feature
- add dtype argument to delete_from_iceberg>
- #3077
=> feat: add dtype argument to delete_from_iceberg

awswrangler/data_api/rds.py, awswrangler/data_api/redshift.py, tests/unit/test_data_api.py
- Feature
- pass params to redshift and rds data api queries
- https://github.com/aws/aws-sdk-pandas/issues/3107
=> feat: add redshift and rds data api query params

awswrangler/_data_types.py
- Bugfix
Because of a bug, we cannot send an uppercase `dtype` parameter to the athena2pyarrow function.
This is due to the fact that this snippet happens prior to lowercasing the `dtype` variable - 
```
if dtype.startswith(("array", "struct", "map")):
orig_dtype: str = dtype
```
I changed the order to make the dtype parameter lowercased before entering this condition, thus even an uppercased ARRAY/STRUCT/MAP type will initialize the orig_dtype variable and avoid the bug.
https://github.com/aws/aws-sdk-pandas/issues/3121
=> fix: Changing dtype lowercasing to start of athena2pyarrow function

awswrangler/s3/_read.py, awswrangler/s3/_read_parquet.py, awswrangler/s3/_read_text.py
- Bugfix
- When executing chunked reads over multiple files that contain different categories, category information is lost due to `pd.concat()` not preserving unmatched categories. Luckily, we already have a utility that concatenates data frames and unions categories.
- https://github.com/aws/aws-sdk-pandas/issues/3123
=> fix: concat with union categories

awswrangler/athena/_cache.py
- Bugfix
- Wrapped the loop in `_LocalMetadataCacheManager.get_queries` with a lock to ensure thread safety when accessing the cache. This prevents potential race conditions in multithreaded environments.
- https://github.com/aws/aws-sdk-pandas/issues/3136
=> fix(athena): ensure thread safety when reading local Athena cache
