aws/aws-sdk-pandas

awswrangler/athena/read.py
tests/test_common.py
tests/test_s3_athena.py

reorganize tests

---

Pipfile
Pipfile.lock
README.md
awswrangler/__init__.py
docs/source/conf.py
docs/source/contributing.rst
docs/source/dependencies.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/license.rst
docs/source/limitations.rst
docs/source/rationale.rst
docs/source/usage/index.rst
docs/source/usage/reading.rst
docs/source/usage/writing.rst

first functional documentation page

---

README.md

Add documentation link to README file

---

README.md
awswrangler/common.py
awswrangler/exceptions.py
awswrangler/s3/__init__.py
awswrangler/s3/read/read.py
awswrangler/s3/write/csv.py
docs/source/usage/reading.rst
tests/test_s3_athena.py

Add s3 reading feature

---

Makefile
docs/source/api/awswrangler.redshift.rst
docs/source/api/awswrangler.rst
setup.cfg

Bumping version to 0.0b3!

---

.gitignore
Makefile
Pipfile
Pipfile.lock
awswrangler/athena.py
awswrangler/glue.py
awswrangler/pandas.py
awswrangler/redshift.py
awswrangler/s3.py
awswrangler/session.py
setup.py
tests/sam/template.yaml
tests/test_pandas.py
tests/test_redshift.py
tests/test_s3.py
tests/test_session.py

Redshift load manifest

---

awswrangler/__version__.py
testing/test_awswrangler/test_cloudwatchlogs.py
testing/test_awswrangler/test_pandas.py

Bumping version to 0.0.4

---

awswrangler/athena.py
awswrangler/glue.py
awswrangler/pandas.py
testing/test_awswrangler/test_cloudwatchlogs.py
testing/test_awswrangler/test_pandas.py

Issue #32 
Adding support for lists to Pandas.

Adding support for lists to Pandas

---

README.md
awswrangler/__init__.py
awswrangler/athena.py
awswrangler/data_types.py
awswrangler/glue.py
awswrangler/pandas.py
awswrangler/redshift.py
awswrangler/spark.py
testing/test_awswrangler/test_redshift.py

Adding support for Date data type to load dataframes on Redshift

Adding support for Date data type to load dataframes on Redshift

---

awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Removing Pandas repeated columns

Removing Pandas duplicated columns

---

awswrangler/glue.py
testing/test_awswrangler/test_pandas.py

Improving exception info

---

README.md
awswrangler/__version__.py
awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Issues: #59 #60 
Fixing cast issues

Fixing cast issues

---

README.md
awswrangler/__version__.py
awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Issue #62 
Fixing single-row-by-partition issue

Fixing single-row-by-partition issue

---

awswrangler/athena.py
awswrangler/data_types.py
awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Issue #72 
Fix Pandas.read_sql_athena() for array columns

Fix Pandas.read_sql_athena() for arrays

---

awswrangler/data_types.py
awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py
testing/test_awswrangler/test_redshift.py

issue #58
Add Decimal type support.

add Decimal type support

---

awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Issue #73 
add Pandas.read_parquet()

add Pandas.read_parquet()

---

awswrangler/aurora.py
testing/test_awswrangler/test_pandas.py

Issue #74 
Improving Aurora tests:
- Float
- Decimal

Improving Aurora tests

---

awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Inverting file format and file compression extensions (key prefix)

---

awswrangler/pandas.py
testing/test_awswrangler/test_pandas.py

Issue #111 
Removing regular indexes from the compulsory Int64 cast

Removing regular indexes from the compulsory Int64 cast

---

awswrangler/__init__.py
awswrangler/emr.py
awswrangler/session.py
requirements-dev.txt
testing/test_awswrangler/test_emr.py

Add support for EMR consistent view

Add support for EMR consistent view

---

awswrangler/pandas.py
awswrangler/s3.py
testing/build-image.sh
testing/deploy-cloudformation.sh
testing/start-jupyter.sh
testing/test_awswrangler/test_s3.py

Issue #133 
- Making test_head_object_with_retry public again
- Add documentation
- Add test

Making test_head_object_with_retry public again

---

testing/test_awswrangler/test_pandas.py

Issue #135 
Adding test for sequential overwrites

Adding test for sequential overwrites

---

awswrangler/session.py

fixes https://github.com/awslabs/aws-data-wrangler/issues/154

Use AWS Session Token when available to build a session

---

README.md
docs/source/api.rst
docs/source/index.rst
docs/source/install.rst
docs/source/what.rst

Issue #171
Add notes about the last release and also fix links in the docs

Add notes about the last release and also fix links in the docs #171

---

requirements-dev.txt
testing/test_awswrangler/test_moto.py

Issue #109
Add first tests with moto.

Add first tests with moto #109

---

awswrangler/_data_types.py
testing/test_awswrangler/test_data_lake.py

Fixing casting with char and varchar lengths

Fixing casting with char and varchar lengths

---

README.md
awswrangler/__metadata__.py
testing/test_awswrangler/test_data_lake.py
testing/test_awswrangler/test_metadata.py
testing/test_awswrangler/test_moto.py
tox.ini

Bumping version to 1.0.3

---

awswrangler/catalog.py
testing/test_awswrangler/test_data_lake.py

Issue #188
Add append mode to create_parquet_table and create_csv_table.

Add append mode to create_*_table

---

awswrangler/__init__.py
awswrangler/_utils.py
awswrangler/athena.py
awswrangler/emr.py
awswrangler/s3.py
docs/source/api.rst
requirements-dev.txt
testing/test_awswrangler/test_cloudwatch.py
testing/test_awswrangler/test_data_lake.py
testing/test_awswrangler/test_emr.py
testing/test_awswrangler/test_moto.py
tutorials/15 - EMR.ipynb
tutorials/16 - EMR & Docker.ipynb

Issue #193
Add support for Docker and custom classification on EMR.

Add support for Docker and custom classification on EMR

---

awswrangler/athena.py
awswrangler/emr.py
testing/test_awswrangler/test_data_lake.py
testing/test_awswrangler/test_torch.py
tox.ini

Issue #201
Revisiting Athena encryption and workgroup.

Revisiting Athena encryption and workgroup

---

testing/test_awswrangler/test_db.py

Issue #200 #218 
Add support for:
- Query UUID columns on PostgreSQL.
- Query full NULL columns for all databases.

Add support for query UUID columns on PostgreSQL and full NULL columns for all databases.

---

awswrangler/athena.py
awswrangler/torch.py
testing/test_awswrangler/test_data_lake.py

Issue #203
Add keep_files and ctas_temp_table_name to wr.athena.read_*().

Add keep_files and ctas_temp_table_name to wr.athena.read_*().

---

README.md
docs/source/api.rst
docs/source/index.rst
docs/source/install.rst
docs/source/what.rst

Add legacy docs.

---

awswrangler/s3.py

#237
parse the response of `client_s3.delete_objects(Bucket=bucket, Delete={"Objects": batch})` in `_delete_objects`.

raise Exception if delete_objects failed

---

docs/source/install.rst

*Description of changes:* Fixing some minor typos under the Glue Wheel section of install doc

Fix typos in install doc

---

awswrangler/s3.py

#256
rename the variable `desc_list`.

refactor naming

---

testing/test_awswrangler/test_moto.py

#254
Add tests for `describe_objects`

add tests for describe objects

---

testing/test_awswrangler/test_moto.py

#254 
Add test cases for other object related functions.

add test cases

---

awswrangler/_data_types.py
testing/test_awswrangler/test_data_lake.py

Fix bug to write partitions in reverse order.

Fix bug to write partitions in reverse order.

---

awswrangler/athena.py

Small fix in the athena docstring.

---

awswrangler/s3/_delete.py
awswrangler/s3/_describe.py
awswrangler/s3/_list.py
awswrangler/s3/_read.py
tests/test_s3_athena.py

*Issue #274, if available: https://github.com/awslabs/aws-data-wrangler/issues/274
I am changing the variable name LastModified to the correct python format last_modified

Changin the lastmodified variable name #274

---

awswrangler/catalog.py
tests/test_athena.py
tests/test_moto.py

#305
add a new function called `get_partitions` and its tests.

add get_partitions

---

awswrangler/catalog.py
awswrangler/db.py

- Add two missing type annotations in catalog.py.
- Fix return type in three docstrings to be in sync with the type annotations in catalog.py and db.py.

Add missing type annotations and fix types in docstrings.

---

README.md
awswrangler/__init__.py
awswrangler/_config.py
awswrangler/_utils.py
awswrangler/athena/_read.py
awswrangler/athena/_utils.py
awswrangler/catalog.py
awswrangler/exceptions.py
tests/test_config.py
tutorials/021 - Global Configurations.ipynb

Adding configuration mechanism.

Adding configuration mechanism

---

awswrangler/athena/__init__.py
awswrangler/athena/_utils.py
tests/_utils.py
tests/test_athena.py

Issue #306 
Add `athena.describe_table` function. The result of the function will be equal to `catalog.table`

Add ddl describe table

---

awswrangler/athena/_utils.py

updated docs

---

awswrangler/athena/__init__.py
awswrangler/athena/_utils.py
tests/test_athena.py

#306 
add show create table function and unit test

add show create table

---

README.md

Add M4U as current Data Wrangler user

---

README.md

Updated README with Serasa Experian user

---

README.md

Add who use aws-data-wrangler
add profile

Add who use wr

---

README.md

* update who use
* remove underscore

Add who use wr (#347)

---

README.md
awswrangler/athena/_read.py
awswrangler/catalog/_add.py
docs/source/conf.py
docs/source/index.rst
tests/test_athena_parquet.py
tutorials/022 - Writing Partitions Concurrently.ipynb

Added corresponding test function  "test_to_parquet_sanitize" in test_athena_parquet.py

Sanitize table name

---

tutorials/002 - Sessions.ipynb

**Issue #, if available:** n/a
**Description of changes:** I am proposing an edit to this sentence to improve readability.

Update 002 - Sessions.ipynb

---

awswrangler/_data_types.py
tests/test_athena_parquet.py

362
Remove double conversion to string, which is no longer necessary and creates "nan" strings

Fix NaN in string columns issue #362

---

README.md

Adding companies that are using AWS Data Wrangler. 

Adding companies using Data Wrangler

---

README.md
awswrangler/__metadata__.py
awswrangler/_utils.py
awswrangler/s3/_read_parquet.py
pytest.ini
tests/test_metadata.py
tests/test_s3_parquet.py

Bumping version to 1.9.2

---

README.md
awswrangler/__metadata__.py
awswrangler/s3/_read_parquet.py
tests/test_metadata.py
tests/test_s3_parquet.py

Fix bug for read_parquet with timezone offset. #385

---

README.md
awswrangler/__metadata__.py
awswrangler/s3/_read_parquet.py
tests/test_metadata.py
tests/test_s3_parquet.py

* supporting wildcard matching
* tweaking type hinting
* removing extra line breaks
* improving return for legibility
* validation shell script changes
* mypy fixes
* further tweaks to type hinting
* Fix bug for read_parquet with offset timezones. #385
Co-authored-by: Nick Miles <nicholasmi@zillowgroup.com>
Co-authored-by: Igor Tavares <igorborgest@gmail.com>

Adding myself to the "who is using" (#389)

---

README.md

Added Funcional Health Tech on "Who is using"

---

README.md
awswrangler/__metadata__.py
awswrangler/_data_types.py
awswrangler/athena/_read.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
requirements-dev.txt
requirements.sh
tests/test_athena.py
tests/test_athena_csv.py
tests/test_athena_parquet.py
tests/test_metadata.py
tests/test_s3_parquet.py
tutorials/006 - Amazon Athena.ipynb

Bumping version to 1.9.5

---

README.md
awswrangler/catalog/_get.py

*Description of changes:* Add the ability to connect with the glue data catalog with [encrypted password connection](https://docs.aws.amazon.com/glue/latest/webapi/API_ConnectionPasswordEncryption.html).
The current aws-data-wrangler version (1.9.5) does not manage encrypted password so it raises exception:
```python
>>> import awswrangler
>>> engine = awswrangler.catalog.get_engine(connection="** some encrypted glue connection **")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "****/awswrangler/catalog.py", line 913, in get_engine
password: str = quote_plus(details["PASSWORD"])
KeyError: 'PASSWORD'
```

Add encrypted glue connection management

---

README.md

Add nrd.io and strongDM to 'who uses' README

---

awswrangler/_config.py
tests/test_config.py

Add workgroup global config. #437

---

README.md

*Description of changes:* add ringDNA to list of users

add ringDNA to list of users

---

awswrangler/redshift.py
tests/test_redshift.py
tutorials/008 - Redshift - Copy & Unload.ipynb

Adding S3 path validation for Redshift COPY.

---

README.md
awswrangler/__init__.py
awswrangler/_databases.py
awswrangler/mysql.py
awswrangler/postgresql.py
awswrangler/redshift.py
awswrangler/secretsmanager.py
cloudformation/databases.yaml
docs/source/api.rst
tests/test_mysql.py
tests/test_postgresql.py
tests/test_redshift.py

Add secretmanager module and support for databases connections. #402

---

awswrangler/_data_types.py
tests/test_athena_parquet.py

Fix nested struct append.

---

awswrangler/_data_types.py

Removing print statement. Found this after random data types started showing up all over my logs.

Remove print statement

---

awswrangler/redshift.py
tests/test_redshift.py

Add tests for the new redshift credentials approaches.

---

tests/test_redshift.py

Add one more redshift test for columns length #280

---

README.md
awswrangler/__metadata__.py
awswrangler/s3/__init__.py
awswrangler/s3/_fs.py
awswrangler/s3/_read_excel.py
awswrangler/s3/_write_excel.py
awswrangler/s3/_write_text.py
docs/source/api.rst
requirements-dev.txt
requirements-docs.txt
requirements.txt
tests/test_fs.py
tests/test_metadata.py
tests/test_s3_excel.py
tests/test_sqlserver.py
tox.ini
tutorials/003 - Amazon S3.ipynb

Add Excel support and some refactoring.

---

awswrangler/redshift.py

Remove Profanity in Redshift Docstrings

---

awswrangler/athena/_read.py
awswrangler/athena/_utils.py
awswrangler/redshift.py
awswrangler/s3/_copy.py
awswrangler/s3/_delete.py
awswrangler/s3/_describe.py
awswrangler/s3/_fs.py
awswrangler/s3/_list.py
awswrangler/s3/_write_excel.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
awswrangler/sqlserver.py

*Issue #562*
*Description of changes:* Add ExpectedBucketOwner as botocore kwarg

Add ExpectedBucketOwner as botocore kwarg

---

awswrangler/s3/_copy.py
awswrangler/s3/_delete.py
awswrangler/s3/_describe.py
awswrangler/s3/_list.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/s3/_write_parquet.py
awswrangler/sqlserver.py
setup.py

*Issue #564:*
Add documentation on how to escape Unix wildcard characters for path parameters.

Add wildcard documentation

---

README.md

Update README.md with NBCUniversal usage.

---

README.md

Add Magnataur to Companies listed in README.md

---

awswrangler/postgresql.py

*Issue #630:*
Accept `postgres` as connection kind.

Add postgres as accepted connection kind

---

awswrangler/athena/_utils.py

*Issue #625 :*
Check if `ResultConfiguration` is present in the workgroup config and if not set the related configuration to `None`.

Add default workgroup result configuration

---

awswrangler/cloudwatch.py

Changing `end_time` parameter to use UTC time aswell (same as start_time).

Change end_time to utc

---

awswrangler/athena/_utils.py

#735
Add `wait_until_exists` to ensure Athena bucket was created

Wait for Athena bucket exists

---

awswrangler/catalog/_get.py
awswrangler/redshift.py
requirements-dev.txt

*Issue #* N/A
Dependabot PR's combined.

Upd dependencies

---

awswrangler/s3/_write_text.py

*Issue: #781* 
Safeguard against missing table details (storage descriptor / location).

Handle missing table location

---

awswrangler/athena/_utils.py

#813
Handle exception where parallel executions attempt to concurrently create an Athena bucket

Minor - Catching OperationAborted exception

---

.bumpversion.cfg
CONTRIBUTING_COMMON_ERRORS.md
README.md
awswrangler/__metadata__.py
awswrangler/athena/_read.py
awswrangler/data_api/rds.py
awswrangler/data_api/redshift.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
docs/source/api.rst
docs/source/install.rst
docs/source/what.rst
pyproject.toml
test_infra/pyproject.toml
tests/test_metadata.py
tutorials/001 - Introduction.ipynb
tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server.ipynb
tutorials/014 - Schema Evolution.ipynb
tutorials/021 - Global Configurations.ipynb
tutorials/022 - Writing Partitions Concurrently.ipynb
tutorials/023 - Flexible Partitions Filter.ipynb
tutorials/030 - Data Api.ipynb

Preparing release 2.11.0

---

awswrangler/_utils.py
awswrangler/catalog/_create.py
awswrangler/s3/_write.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
tests/test_catalog.py
tests/test_s3_text.py

Issue #868 
Fix CSV schema evolution in `wr.s3.to_csv` + add schema evolution parameter to `wr.catalog.create_table`.

Fix csv schema evolution

---

awswrangler/emr.py

#889 
Adding step concurrency parameter to EMR `run_job_flow` method

Minor - Adding EMR step concurrency

---

poetry.lock
pyproject.toml

*Issue #, if available:* N/A
Update dependencies

Update tox / sphinx

---

awswrangler/emr.py

*Issue #907 *
Add custom AMI id parameter

EMR - add custom AMI id param

---

awswrangler/s3/_write_parquet.py

Issue #592 
Pass additional arguments to pyarrow

Pass additional arguments to pyarrow

---

awswrangler/catalog/_utils.py

Minor - Adding Catalog Id to does exist method

---

awswrangler/timestream.py

Minor - Handling None in timestream

---

building/lambda/build-lambda-layer.sh
poetry.lock
pyproject.toml

Upgrading dependencies

---

awswrangler/catalog/_delete.py
docs/source/install.rst

#975
- Fixed _catalog_id in get_table call of delete_colum
- Moved SAR section to layers in docs

Minor - Fixing catalog id in delete col + update docs

---

awswrangler/catalog/_create.py

Minor - Fix missing parameters key

---

poetry.lock
pyproject.toml
tox.ini

Python 3.10 support

---

building/build-lambda-layers.sh
building/lambda/build-docker-images.sh

*Issue #906 *
Adding 3.9 layer images using `ublic.ecr.aws/sam/build-python3.9:latest` as base

Add 3.9 layer images

---

awswrangler/redshift.py

Add missing commas to fix the Redshift examples

Add missing commas

---

awswrangler/catalog/_add.py

Fix None column comment

---

awswrangler/catalog/_add.py
awswrangler/catalog/_definitions.py
tests/test_catalog.py

#1016
Adding `partitions_parameters` argument to catalog partitions methods

Minor - Adding partition params

---

awswrangler/s3/_write_text.py
poetry.lock
tests/test_moto.py

#1072
- Upgrading dependencies seems to fix moto tests
- Adding missing `pandas_kwargs` to `to_json`

Minor - Adding missing pd kwargs in to_json

---

docs/source/install.rst

Docs - add lambda layers table

---

test_infra/stacks/databases_stack.py

Hotfix - Infra Security Group Incoming traffic

---

awswrangler/_databases.py
awswrangler/mysql.py
awswrangler/postgresql.py
awswrangler/redshift.py
awswrangler/sqlserver.py
tests/test_postgresql.py

#1130
Add timestamp as object to database methods

Add timestamp as object to database methods

---

.bumpversion.cfg
CONTRIBUTING_COMMON_ERRORS.md
README.md
awswrangler/__metadata__.py
awswrangler/athena/_read.py
awswrangler/s3/_list.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
docs/source/install.rst
docs/source/what.rst
poetry.lock
pyproject.toml
test_infra/pyproject.toml
tests/test_metadata.py
tutorials/001 - Introduction.ipynb
tutorials/007 - Redshift, MySQL, PostgreSQL, SQL Server.ipynb
tutorials/014 - Schema Evolution.ipynb
tutorials/021 - Global Configurations.ipynb
tutorials/022 - Writing Partitions Concurrently.ipynb
tutorials/023 - Flexible Partitions Filter.ipynb

Preparing release 2.14.0

---

.github/workflows/git-hygiene.yml

Subject: Updating Stale Issue Workflow
Using action: https://github.com/actions/stale

Issue hygiene workflow

---

.github/workflows/needs-response.yml

-  Adding new workflow for labeling issues without response

Github Actions: Adding new workflow for labeling issues without response

---

awswrangler/_data_types.py

- Feature
- Warn about implicit float conversion
- #1115 

Add warning for implicit float conversion

---

README.md

Adding VTEX as a happy user

---

awswrangler/emr.py

Fix #1253
- Bugfix
#1253
#1253

fix: build spark step load right deploy type

---

awswrangler/catalog/_delete.py

- Bugfix
- Documentation for delete_database says it creates a database, I changed it to delete the database instead.

Minor: Fix delete_database doc

---

tutorials/004 - Parquet Datasets.ipynb
tutorials/011 - CSV Datasets.ipynb

- Bugfix
- fixing a minor typo in the tutorials

[skip ci] (minor) (docs) partitoned → partitioned

---

awswrangler/athena/_read.py
awswrangler/sqlserver.py
tests/test_sqlserver.py
tutorials/006 - Amazon Athena.ipynb

- Feature
- Add fast_executemany mode
- Fix some docs issues
- #1293 

Feat fast executemany

---

awswrangler/athena/_utils.py

- Feature
- add data_source param to athena.repair_table
- #1318

add data_source param to athena.repair_table (closes #1318)

---

awswrangler/quicksight/_create.py
tests/_utils.py
tests/test_quicksight.py
tutorials/018 - QuickSight.ipynb

- Feature
- add TagColumnOperation to quicksight.create_athena_dataset
#1340

add TagColumnOperation to quicksight.create_athena_dataset

---

awswrangler/athena/_utils.py
awswrangler/timestream.py
tests/test_timestream.py

- Feature
- added list_databases and list_tables functions to awswrangler.timestream module
- #1337 

enable list timestream databases and tables

---

awswrangler/distributed/__init__.py
awswrangler/distributed/_utils.py
awswrangler/lakeformation/_read.py

- Feature
- Enable distribution on LF read method 

(feat): Lake Formation read distributed implementation

---

tests/test_catalog.py

- Bugfix
- Mark intermittent test failure as xfail
- #1451

(fix): Mark intermittent test failure as xfail

---

awswrangler/catalog/_create.py

- Bugfix
- Missing catalog_id in create_database
- #1473

Missing catalog_id in create_database

---

awswrangler/_databases.py

- Bugfix
- Cast database connection port to int
- #1484

(fix): Cast db connection port to int

---

README.md

Adding Fortescue Future Industries to the support list. Keep up the great work team!

Support Data Wrangler

---

awswrangler/s3/_delete.py
tests/test_s3.py

Bugfix
- s3 delete tests failing in distributed codebase
- #1516 

bug: s3 delete tests failing in distributed codebase

---

tests/test_opensearch.py
tests/test_timestream.py
tox.ini

testing renamed ci tests

---

awswrangler/quicksight/_create.py

Fix wrong type hint for TagColumnOperation in quicksight.create_athena_dataset

---

poetry.lock
pyproject.toml

update wheel library as it is causing issues in some environments

---

tutorials/006 - Amazon Athena.ipynb
tutorials/008 - Redshift - Copy & Unload.ipynb
tutorials/010 - Parquet Crawler.ipynb
tutorials/019 - Athena Cache.ipynb
tutorials/022 - Writing Partitions Concurrently.ipynb

- `noaa-ghcn-pds` bucket has changes partinioning

Tutorials Updating S3 Paths for Bucket `noaa-ghcn-pds`

---

awswrangler/_data_types.py
awswrangler/athena/_utils.py
tests/test_athena.py

Cast Athena array, map & struct types to pandas object

---

.github/workflows/cfn-nag.yml

add env var placeholders for cfn-nag

---

.github/workflows/cfn-nag.yml

avoid cdk synth retrieving az list using credentials
- Bugfix

cfn-nag workflow: add us-east az list to cdk.context.json

---

.github/workflows/bandit.yml
.github/workflows/minimal-tests.yml
.github/workflows/static-checking.yml

bandit, minimal-tests, static-checking workflows: update actions images

---

docs/source/install.rst

- Bugfix
- The install page is referencing the old layer name

Update install page in documentation

---

awswrangler/athena/_read.py
tests/test_athena_parquet.py

- Enhancement
- Add missing unload_approach and unload_parameters to athena.read_sql_table

(enhancement): Add unload_approach to athena.read_sql_table

---

awswrangler/s3/_write_dataset.py

(feat) Add partitioning on block level

---

poetry.lock
pyproject.toml
tests/_utils.py

- Dependencies
- Uptick modin to 0.16
- Widen range for pyarrow

Uptick modin to 0.16

---

README.md
docs/source/about.rst
docs/source/install.rst
tutorials/034 - Distributing Calls using Ray.ipynb
tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb

- Add an `At scale` section in README
- Improve tutorials 34 and 35
Note that both tutorials were tested.

(docs): Improve documentation on running SDK for pandas at scale

---

awswrangler/distributed/ray/modin/_core.py

(feat) validate partitions along row axis, add warning

---

awswrangler/_arrow.py
awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
awswrangler/distributed/ray/datasources/parquet_datasource.py
awswrangler/distributed/ray/modin/s3/_read_parquet.py
awswrangler/distributed/ray/modin/s3/_write_parquet.py
awswrangler/s3/_write_parquet.py
tests/_utils.py
tests/unit/test_s3_parquet.py

(feat) distrib parquet - add missing features, enable all tests

---

awswrangler/distributed/ray/datasources/__init__.py
awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
awswrangler/distributed/ray/modin/s3/_read_parquet.py
awswrangler/distributed/ray/modin/s3/_write_parquet.py

- Convention
- Add Arrow prefix to parquet datasource for consistency

(convention): Add Arrow prefix to parquet datasource for consistency

---

awswrangler/distributed/ray/_register.py
awswrangler/s3/_describe.py
awswrangler/s3/_read.py

Reverts aws/aws-sdk-pandas#1744
Some CB tests failing so reverting for now as too risky

Revert "(feat): Distribute describe_objects S3 method"

---

docs/source/api.rst

(docs) add distributed / ray api docs

---

awswrangler/s3/_read.py

(fix) Allow read partitions with extra = in the value

---

awswrangler/_utils.py
awswrangler/exceptions.py
awswrangler/s3/_select.py

- Feature
- Retry on inexplicably missing "End" events from S3 select response 

(feat) s3 select - add retries

---

awswrangler/_config.py
awswrangler/distributed/ray/_core.py

- Logging
- Set ray logger level to INFO
- Enable user to disable/enable the RayLogger and override its logging level

(logging): Enable user to configure RayLogger

---

awswrangler/athena/_utils.py

- Bugfix
- The SQL formatting in `start_query_execution` was incorrect

Fix SQL formatting for start_query_execution

---

awswrangler/distributed/ray/modin/_utils.py
tests/unit/test_s3_parquet.py

(fix) Minor - empty arrow refs

---

awswrangler/catalog/_create.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
tests/unit/test_athena_projection.py
tutorials/017 - Partition Projection.ipynb

(enhance) Consolidate partition projection params for wr.s3.to_* and wr.catalog.create_*

---

awswrangler/s3/_read_parquet.py

(fix) Check if timezone is present in column metadata

---

test_infra/stacks/opensearch_stack.py

(test-infra) Enable SSE, enforce HTTPS, enable node-to-node encryption

---

awswrangler/_utils.py
awswrangler/mysql.py
awswrangler/opensearch/_write.py
awswrangler/postgresql.py
pyproject.toml

- Refactoring
- Enable `warn_unused_ignores` for MyPy

Enable warn_unused_ignores for MyPy

---

awswrangler/distributed/ray/_core.py
awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
poetry.lock
pyproject.toml
tests/unit/test_s3_parquet.py

Upgrading PyArrow to 7+ so that we can merge the DeltaLake feature into `release-3.0.0`.

Upgrade Ray to 2.2.x and PyArrow to 7+

---

awswrangler/_utils.py
tests/test_data_quality.py

- Feature
- Add unit test for evaluating two rulesets at once

Add unit test for evaluating two rulesets at once

---

awswrangler/redshift.py

(enhancement) Minor - wr.redshift.copy - pass through commit_transaction

---

awswrangler/opensearch/_read.py
tests/test_opensearch.py

(fix) Minor - KeyError in wr.opensearch.seach && cleanup tests

---

tests/conftest.py
tests/test_moto.py

- Increase coverage for `awswrangler/dynamodb/_write.py`

Increase coverage for dynamodb write

---

tests/test_s3_wait.py

- Increased coverage of `s3/_wait` module from 34% to 100%

Add tests for S3 wait functions

---

tests/test_s3.py

- Increase coverage for `awswrangler.s3._delete` module

Increase coverage for s3.delete*

---

tests/_utils.py
tests/load/test_databases.py
tests/load/test_s3.py

- Feature
- Refactoring
- Leverage pytest `request` to obtain test name
- Add commit branch and hash to data
- Write load tests to a single file

(enhancement): Simplify load tests framework

---

awswrangler/s3/_read.py
tests/unit/test_s3.py

* Added tests to increase coverage
* Removed some unused code

Increase coverage for S3 list and read

---

awswrangler/s3/_write_text.py
tests/test_s3_excel.py
tests/test_s3_select.py
tests/test_s3_text.py

- Coverage
- Increase coverage of some S3 tests

Increase S3 tests coverage

---

awswrangler/__init__.py
awswrangler/redshift.py

(enhancement) unload ray default max file size

---

awswrangler/quicksight/_delete.py
tests/test_quicksight.py

- Adding filter to quicksight `delete_all` methods

enhancement: Adding filter to quicksight `delete_all` methods

---

awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
tests/unit/test_athena_parquet.py

- Change `sanitize_columns` to no longer modify original DataFrame
- https://github.com/aws/aws-sdk-pandas/issues/1914

Change sanitize_columns to no longer modify original DF

---

awswrangler/_distributed.py
awswrangler/_utils.py
awswrangler/distributed/ray/_register.py
awswrangler/distributed/ray/modin/_utils.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py

- Bugfix
- Fix sanitize column names modifying the data frame in distributed mode

Fix sanitize column names modifying the data frame in distributed mode

---

tox.ini

- Adding minimum coverage. The build will fail if the coverage drops below 88
- For distributed mode, a separate value will be added

Add minimum coverage

---

tests/conftest.py
tests/test_quicksight.py

refactor: quicksight test resources as fixtures

---

awswrangler/s3/_write_parquet.py

(enhancement) Minor - allow override ParquetWriter args

---

awswrangler/emr.py

(enhancement) Minor - add EMR configurations arg

---

awswrangler/s3/_read_text.py

- Feature
- Add missing overload for `read_fwf`

Add missing overload for read_fwf

---

awswrangler/dynamodb/_read.py
tests/test_dynamodb.py

- Feature
- Add index_name to DynamoDB read_items
- #1958

(feat): Add index_name to DynamoDB read_items

---

awswrangler/opensearch/_read.py
awswrangler/opensearch/_write.py

- Bugfix
- Set Content-Type to lowercase
- #1965

(fix): Content Type in lowercase

---

awswrangler/s3/_write_parquet.py

- Add ability to pass arguments to `ParquetWriter.write_table` such as `row_group_size`
- #913 

(enhancement) Add write_table_args

---

awswrangler/_data_types.py

- Bugfix
- Support uuid in `athena2pyarrow` mapping
- #1975

(fix): Add uuid to athena2pyarrow mapping

---

test_infra/poetry.lock
test_infra/pyproject.toml
test_infra/stacks/opensearch_stack.py
tests/test_opensearch.py

- Move AOSS collection to infra
- Upgrade CDK version & update poetry.lock

(tests) Move AOSS collection to infra

---

awswrangler/_config.py
awswrangler/_distributed.py
awswrangler/_sql_formatter.py
awswrangler/_threading.py
awswrangler/_utils.py
awswrangler/athena/_read.py
awswrangler/athena/_utils.py
awswrangler/catalog/_utils.py
awswrangler/data_api/rds.py
awswrangler/distributed/ray/_core.py
awswrangler/distributed/ray/_register.py
awswrangler/distributed/ray/datasources/arrow_csv_datasource.py
awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
awswrangler/distributed/ray/datasources/pandas_text_datasource.py
awswrangler/distributed/ray/modin/_data_types.py
awswrangler/dynamodb/_read.py
awswrangler/dynamodb/_utils.py
awswrangler/emr.py
awswrangler/lakeformation/_read.py
awswrangler/opensearch/_write.py
awswrangler/postgresql.py
awswrangler/s3/_fs.py
awswrangler/s3/_select.py
awswrangler/s3/_upload.py
awswrangler/s3/_write_dataset.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
awswrangler/timestream.py

- Refactoring
- Reduced the scope of `type: ignore` statements to specify which error is being ignored.
- 

Reduce scope of "# type: ignore"

---

test_infra/stacks/base_stack.py

(tests) Glue Data Quality Role - add missing LakeFormation permissions

---

awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py

Set ray.data parallelisation to -1 by default

---

test_infra/poetry.lock

- `poetry.lock` was incorrectly merged in #2020 
- regenerating here

fix: `poetry.lock` merge issue

---

tests/test_s3.py
tests/test_s3_text.py

(tests) Fix SSE defaults

---

CONTRIBUTING.md
tests/test_fs.py

- Enhancement
Contributing guide is outdated. Successfully tested `Mocked Tests` section on my local machine.
- Fix contributing guide
- #2035

docs: fix contributing guide

---

README.md
awswrangler/_utils.py
awswrangler/distributed/ray/_register.py
awswrangler/s3/_describe.py
awswrangler/s3/_fs.py

- Enhancement
- Distribute S3 describe_objects
- Handle edge case of custom S3 fs

enhancement: Distribute S3 describe_objects

---

README.md
awswrangler/distributed/ray/_register.py
awswrangler/s3/_copy.py

(feat) Distributed S3 copy/merge

---

awswrangler/_config.py

- Refactoring
- Change `suppress_warnings` to `bool` with default value

Change `suppress_warnings` to `bool` with default value

---

README.md
awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
awswrangler/distributed/ray/modin/s3/_read_text.py
awswrangler/dynamodb/_read.py
awswrangler/lakeformation/_read.py
awswrangler/s3/_delete.py
awswrangler/s3/_describe.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/s3/_select.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
building/update-glue-lib.sh
tutorials/001 - Introduction.ipynb
tutorials/037 - Glue Data Quality.ipynb
tutorials/038 - OpenSearch Serverless.ipynb

- Enhancement
- Simplify logging calls to avoid verbose logs in distributed mode. For instance, avoid printing the full list of paths
- Fix how the package is zipped for Glue on Ray jobs
- Reorganise the tutorials numbering to solve conflicts

chore: Simplify logging, fix zip bundling and reorganise tutorials

---

awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
poetry.lock
pyproject.toml

deps: Upgrade ray to 2.3

---

awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/typing.py
tests/load/test_s3.py
tests/unit/test_s3_parquet.py

- Refactoring
- Extract `parallelism` and `bulk_read` into `ray_modin_args`
Closes #2063 

Extract `parallelism` and `bulk_read` into `ray_modin_args`

---

awswrangler/distributed/ray/modin/s3/_read_parquet.py
tests/unit/test_s3.py
tests/unit/test_s3_parquet.py
tests/unit/test_s3_select.py
tests/unit/test_s3_text_compressed.py

- Refactoring
- Narrow down `xfail` statements in our unit tests

Narrow down `xfail` statements in our unit tests

---

awswrangler/timestream.py

fix: timestream empty batches

---

awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py

docs: Minor - clarify datasource.on_write_complete docs

---

.github/workflows/pr-linter.yml

- GH action
- Add PR linter Github action

tests: Add PR linter Github action

---

awswrangler/_utils.py
awswrangler/distributed/ray/_register.py
awswrangler/distributed/ray/_utils.py
awswrangler/dynamodb/_read.py
tests/load/test_dynamodb.py

- Feature
- Add `parallelism` parameter to `dynamodb.read_items`
- Add load test for DynamoDB

feat: `dynamodb.read_items` `use_theads` parameter & load test

---

awswrangler/_executor.py
awswrangler/distributed/ray/_executor.py
awswrangler/distributed/ray/_register.py
awswrangler/dynamodb/_read.py
awswrangler/lakeformation/_read.py
awswrangler/s3/_copy.py
awswrangler/s3/_delete.py
awswrangler/s3/_describe.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/s3/_select.py
awswrangler/s3/_wait.py
awswrangler/timestream.py

refactor: executor module

---

tutorials/036 - Athena Iceberg.ipynb

tutorials: Athena Iceberg

---

awswrangler/_config.py
tests/test_config.py

- Bugfix
- Fix config not loading environment variables for config
- Fixes #2135

fix: Config not loading environment variables for config

---

tests/test_redshift.py

- Testing
- A customer was asking if this feature was supported. I had to write the test to make sure that it did indeed work.

test: Adding the Redshift `test_to_sql_with_identity_column` unit test

---

tests/test_opensearch.py

- Move index cleanup into finally blocks
- Skip instead of xfail

tests: opensearch index cleanup / skip

---

README.md
docs/source/conf.py
docs/source/index.rst
docs/source/scale.rst
tutorials/034 - Distributing Calls using Ray.ipynb
tutorials/035 - Distributing Calls on Ray Remote Cluster.ipynb

docs: Add @scale section

---

awswrangler/s3/_write.py
awswrangler/s3/_write_parquet.py
awswrangler/s3/_write_text.py
tests/test_s3.py

fix: Sanitize bucketing col names

---

awswrangler/_executor.py
awswrangler/distributed/ray/_executor.py
awswrangler/dynamodb/_delete.py
awswrangler/dynamodb/_read.py
awswrangler/dynamodb/_write.py
awswrangler/timestream.py
tests/conftest.py
tests/unit/test_timestream.py

- Refactoring
- Improve logging for `dynamodb` and `timestream` modules

chore: Logging improvements

---

awswrangler/athena/_read.py
tests/test_athena.py

fix: Athena out of bound dates

---

README.md

- Bugfix
- Fix URL that no longer exists.

Fix about URL

---

building/build-lambda-layers.sh
building/lambda/build-docker-images.sh

- Feature
- Add builds for Python 3.10 layers

build: Add builds for Python 3.10 layers

---

docs/source/install.rst

- Update SAR section of install documentation

docs: Update SAR section of install documentation

---

awswrangler/s3/_select.py
tests/unit/test_s3_select.py

feat: Add ability to pass schema to S3 Select

---

awswrangler/postgresql.py
tests/unit/test_postgresql.py

feat: Add support for server-side cursors in postgresql module

---

tutorials/033 - Amazon Neptune.ipynb

- Add tutorials section for the Neptune bulk load

docs: Add tutorials section for the Neptune bulk load

---

awswrangler/data_api/rds.py
docs/source/api.rst

- Add page for `data_api.rds.to_sql`

docs: Add page for data_api.rds.to_sql

---

awswrangler/athena/_cache.py

- Bugfix
- Fix KeyError
- Add lock to cache manager to avoid race cond when updating cache
- #2296 

fix: KeyError & add lock to athena cache manager

---

awswrangler/neptune/_client.py
tests/unit/test_neptune.py

- Feature
- Neptune bulk load bad request

fix: Neptune bulk load bad request

---

awswrangler/_distributed.py
awswrangler/distributed/ray/_core.py
awswrangler/distributed/ray/_register.py
awswrangler/distributed/ray/modin/s3/_read_parquet.py
awswrangler/distributed/ray/modin/s3/_read_text.py
awswrangler/s3/_read_parquet.py
awswrangler/s3/_read_text.py
awswrangler/s3/_write_parquet.py

- Refactoring
- We had a few places where the signatures of the source function and the dispatch function did not match. I added a way where MyPy will automatically find those mismatches

refactor: engine `register_func` to handle type checking

---

awswrangler/data_quality/_utils.py
awswrangler/distributed/ray/datasources/pandas_file_based_datasource.py
poetry.lock
tests/benchmark/test_glueray.py
tests/unit/test_s3.py

- Bugfix
- adapt benchmark tests to Glue for Ray GA breaking changes

fix: adapt benchmark tests to Glue for Ray GA breaking changes

---

tutorials/026 - Amazon Timestream.ipynb

- Tutorial Example
- Add multi measure write record example for Timestream

feat: Timestream Add multi measure write record example

---

awswrangler/athena/_write_iceberg.py
tests/unit/test_athena.py

- Feature
- Add support for Iceberg `PARTITIONED BY`
- #2318 

feat: Iceberg `PARTITIONED BY` and additional table properties support

---

awswrangler/dynamodb/_read.py
tests/unit/test_dynamodb.py

- Bugfix
When supplying the `Limit` argument in a DynamoDB Query/Scan operation, a `LastEvaluatedKey` is returned even when the limit is reached. See the note [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.Pagination). This caused the read_items API to scan the entire table instead of returning the specified `max_items_evaluted` rows.
- Break the Scan/Query when limit is reached
- enforce use_threads=False when Limit is supplied
- #2371

fix: enforce use_threads=False when Limit is supplied

---

test_infra/poetry.lock
test_infra/stacks/databases_stack.py
tests/conftest.py

- Feature
- Adding prerequisite infra for improving coverage of data api tests (to cover postgresql serverless)
- #2385 

test: Add Aurora PostgreSQL Serverless

---

awswrangler/data_api/rds.py
tests/unit/test_data_api.py

- Bugfix
- RDS Data API module at the moment uses backticks in the queries that aren't compatible with PostgreSQL engine. On the other hand, MySQL uses backticks by default and does not guarantee enabled ANSI mode (`SET sql_mode='ANSI_QUOTES'`). To avoid breaking changes and keep MySQL-compatibility, keep using backticks by default, but allow to override the SQL mode using `sql_mode` parameter.
- Add a test case for PostgreSQL Serverless.
- Adds a test case using ANSI SQL mode with MySQL.
- #2385

fix: RDS Data API - allow ANSI-compatible identifiers.

---

awswrangler/athena/_write_iceberg.py

Signed-off-by: Abdel Jaidi <jaidisido@gmail.com>
- Bugfix
- add missing boto3 session in to_iceberg wait_query
- #2427

fix: add missing boto3 session in to_iceberg wait_query

---

awswrangler/athena/_write_iceberg.py

- Bugfix
- add catalog id in Athena to_iceberg
- #2441

fix: add catalog id in Athena to_iceberg

---

docs/source/scale.rst
tests/glue_scripts/wrangler_blog_simple.py
tutorials/029 - S3 Select.ipynb
tutorials/034 - Distributing Calls using Ray.ipynb

fix: Replace deprecated dataset in tutorials and docs

---

awswrangler/athena/_cache.py
awswrangler/athena/_executions.py
awswrangler/athena/_read.py
awswrangler/athena/_utils.py
tests/unit/test_athena_cache.py
tox.ini

- Feature
- Add support for `client_request_token` in Athena methods
- Minor refactoring of cache checks - removed copy-paste
- Add test case
- https://github.com/aws/aws-sdk-pandas/issues/2473

feat: Athena - add `client_request_token`

---

awswrangler/neptune/_neptune.py

- Bugfix
- Insert exact batch size
- #2494 

fix: Gremlin batch size calc

---

awswrangler/athena/_write_iceberg.py
tests/unit/test_athena.py

- Feature
- Adding an optional parameter to `to_iceberg` for performing `MERGE INTO` operations
- #2523

feat: Add MERGE INTO support for Iceberg

---

awswrangler/_sql_utils.py
awswrangler/data_api/rds.py
awswrangler/mysql.py
awswrangler/oracle.py
awswrangler/postgresql.py
awswrangler/sqlserver.py

fix: Sql identifiers

---

.github/workflows/static-checking.yml
awswrangler/__init__.py
awswrangler/athena/__init__.py
awswrangler/catalog/__init__.py
awswrangler/distributed/ray/__init__.py
awswrangler/distributed/ray/datasources/arrow_parquet_datasource.py
awswrangler/emr.py
awswrangler/lakeformation/__init__.py
awswrangler/pandas/__init__.py
awswrangler/quicksight/__init__.py
awswrangler/s3/__init__.py
awswrangler/s3/_write_dataset.py
fix.sh
pyproject.toml
test_infra/stacks/databases_stack.py
tests/unit/test_athena_parquet.py
tutorials/017 - Partition Projection.ipynb
tutorials/022 - Writing Partitions Concurrently.ipynb
tutorials/023 - Flexible Partitions Filter.ipynb
tutorials/032 - Lake Formation Governed Tables.ipynb
validate.sh

- Consolidate the two `ruff check` commands into a single command
- Add `RUF100` rule which removed unused `noqa` comments
- fix linting errors in Jupyter Notebooks

chore: ruff improvements

---

awswrangler/cleanrooms/_read.py
test_infra/stacks/cleanrooms_stack.py
tests/conftest.py
tests/unit/test_cleanrooms.py

- Feature
- add analysis_template_arn to cleanrooms read_sql_query
- adapt CDK infrastructure
- #2580

feat: add analysis_template_arn to cleanrooms read_sql_query

---

.github/workflows/dependabot-prs.yml

- Enhancement
- Add [metadata to dependabot PRs](https://github.com/dependabot/fetch-metadata?tab=readme-ov-file#usage-instructions), particularly security information (e.g. CVE...)

feat: add dependabot-fetch-metadata action

---

.bumpversion.toml
README.md

- The badges we had in the README which referred to our Python versions and formatter were out of date

chore: update badges in README

---

.github/workflows/dependabot-prs.yml

- Enhancement
- add vulnerability label to dependabot PRs with alert state

fix: add vulnerability label to dependabot PRs with alert state

---

poetry.lock
pyproject.toml

fix: s3fs pinned version

---

tests/unit/test_sqlserver.py

fix: RDS integration test failures

---

test_infra/stacks/databases_stack.py

- https://github.com/aws/aws-sdk-pandas/pull/2670

fix: Tests - move certs to a public bucket

---

tests/unit/test_athena.py
tests/unit/test_s3_parquet.py

- None of the asserts for Athena categories were executing, as the test had an `xfail` that triggered in the very beginning. Splitting the test case into 5 different tests, only 3 of which need the `xfail`

fix: separate tests for Athena categories

---

test_infra/stacks/base_stack.py
tests/conftest.py
tests/unit/test_s3_parquet.py

Add test for `read_parquet` and `to_parquet` using S3 access points

test: Add test for S3 access points

---

tests/unit/test_distributed.py

In our engine switching tests, we weren't resetting to the installed version. This is what has been causing transient test error later down the line (mainly with `test_read_parquet_table_with_client_side_encryption`), as we were running tests in the non-distributed mode, albeit without the required `xfails` active.

test: Fix engine switching reset

---

tests/unit/test_quicksight.py

- Fix transient error in Quicksight unit tests
- This has been causing our UnitTests CodeBuild to fail

test: Fix quicksight unit tests

---

awswrangler/_sql_formatter.py

- Bugfix
- correct athena timezone TypeError message
- closes #2793

fix: correct athena timezone TypeError message

---

CONTRIBUTING.md

- Bugfix
This is a small PR. PR #316 renamed the license file. This PR adjusts sources to this change.

fix: update license reference

---

awswrangler/athena/_write_iceberg.py

- Bugfix
- add missing index in athena.to_iceberg to_parquet
- closes #2782

fix: add missing index in athena.to_iceberg to_parquet

---

.github/workflows/snyk.yml

- add upload for Snyk security scan to GitHub Code Scanning

chore: add upload for Snyk security scan to GitHub Code Scanning

---

awswrangler/s3/_write_dataset.py

- Bugfix
- fix bucketing error with newer version of Modin (0.31.0)

fix: bucketing error with newer version of Modin (0.31.0)

---

docs/source/layers.rst

docs: Update layer versions

---

test_infra/stacks/base_stack.py
test_infra/stacks/glueray_stack.py

- Bugfix
- enforce SSL on tests infra S3 buckets

fix: enforce ssl

---

awswrangler/data_api/redshift.py

fix: add missing raise statement in RS Data API

---

.github/workflows/minimal-tests.yml
poetry.lock

- Bugfix
- Exclude py3.13 Windows minimal test

fix: exclude py3.13 windows minimal test

---

awswrangler/oracle.py
tests/unit/test_oracle.py

- Bugfix
- https://github.com/aws/aws-sdk-pandas/issues/3096

fix: oracle decimal error

---

awswrangler/redshift/_write.py
tests/unit/test_redshift.py

- add test case
- clarify docs
- https://github.com/aws/aws-sdk-pandas/issues/3095

chore: add redshift `COPY` with `SERIALIZETOJSON` test case
